/**
 * SVG -> framework components.
 *
 * Components are generated, never committed. 1000 icons x 2 frameworks is 2000 files
 * that would all have to stay in step with the SVG by hand; the only way to guarantee
 * they never drift is to make drift impossible.
 *
 * Both emitters consume the same IconNode array, so React and Vue cannot diverge in
 * what they draw — only in how they mount it.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { parseSvg, toComponentName, IconMetaInput } from "@iconmind/shared";
import { fromRoot, loadIcons } from "../lib/fs.ts";

type IconNode = [tag: string, attrs: Record<string, string>][];
interface Built { slug: string; name: string; nodes: IconNode; aliases: string[]; deprecated: boolean }

const icons = (await loadIcons()).filter((i) => i.svg && i.json);

const built: Built[] = icons.map((icon) => {
  const meta = IconMetaInput.parse(JSON.parse(icon.json!));
  const { children } = parseSvg(icon.svg);
  return {
    slug: meta.slug,
    name: toComponentName(meta.slug),
    nodes: children.map((c) => [c.tag, c.attrs] as const) as IconNode,
    aliases: meta.aliases,
    deprecated: meta.deprecated !== null,
  };
}).sort((a, b) => a.slug.localeCompare(b.slug));

const nodesLiteral = (nodes: IconNode) =>
  "[\n" + nodes.map(([tag, attrs]) =>
    `  ["${tag}", { ${Object.entries(attrs).map(([k, v]) => `"${k}": "${v}"`).join(", ")} }],`
  ).join("\n") + "\n]";

const BANNER = "// Generated by scripts/generate/components.ts — do not edit.\n";

interface Target { dir: string; ext: string; render: (b: Built) => string }

const react: Target = {
  dir: fromRoot("packages/react/src/generated"),
  ext: "tsx",
  render: (b) =>
    `${BANNER}import { createIcon } from "../create-icon";\n\n` +
    `export const ${b.name} = createIcon("${b.name}", ${nodesLiteral(b.nodes)});\n` +
    b.aliases.map((a) => `\n/** @deprecated use \`${b.name}\` */\nexport const ${toComponentName(a)} = ${b.name};\n`).join(""),
};

const vue: Target = {
  dir: fromRoot("packages/vue/src/generated"),
  ext: "ts",
  render: (b) =>
    `${BANNER}import { createIcon } from "../create-icon";\n\n` +
    `export const ${b.name} = createIcon("${b.name}", ${nodesLiteral(b.nodes)});\n` +
    b.aliases.map((a) => `\n/** @deprecated use \`${b.name}\` */\nexport const ${toComponentName(a)} = ${b.name};\n`).join(""),
};

// Vue is a phase 2 deliverable; the emitter exists so the two can never drift, but it
// only writes when the package is actually there.
const targets = [react, vue].filter((t) => existsSync(t.dir.replace("/src/generated", "")));

for (const t of targets) {
  await rm(t.dir, { recursive: true, force: true });
  await mkdir(t.dir, { recursive: true });

  for (const b of built) {
    await writeFile(`${t.dir}/${b.slug}.${t.ext}`, t.render(b));
  }

  const barrel =
    BANNER +
    built.map((b) => `export { ${b.name}${b.aliases.map((a) => `, ${toComponentName(a)}`).join("")} } from "./${b.slug}";`).join("\n") +
    "\n\n/** Every icon slug, as a union. */\nexport type IconName =\n" +
    (built.length ? built.map((b) => `  | "${b.slug}"`).join("\n") : "  never") + ";\n";
  await writeFile(`${t.dir}/index.${t.ext === "tsx" ? "ts" : "ts"}`, barrel);

  console.log(`${t.dir} — ${built.length} components + barrel`);
}

if (!targets.length) console.log("No framework packages present yet; nothing generated.");
