/**
 * SVG -> framework components.
 *
 * Components are generated, never committed. 1000 icons x 2 frameworks is 2000 files
 * that would all have to stay in step with the SVG by hand; the only way to guarantee
 * they never drift is to make drift impossible.
 *
 * Both emitters consume the same IconNode array, so React and Vue cannot diverge in
 * what they draw — only in how they mount it.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { parseSvg, toComponentName, cellName, IconMetaInput } from "@iconmind/shared";
import { fromRoot, loadIcons } from "../lib/fs.ts";

type IconNode = [tag: string, attrs: Record<string, string>][];
interface Built {
  slug: string; name: string; aliases: string[]; deprecated: boolean;
  /** Every matrix cell this concept has, keyed `variant-weight`. */
  cells: Array<[string, IconNode]>;
  /** The variants it has, for narrowing the component's `variant` prop. */
  variants: string[];
}

const icons = (await loadIcons()).filter((i) => i.svg && i.json);

const built: Built[] = icons.map((icon) => {
  const meta = IconMetaInput.parse(JSON.parse(icon.json!));
  const cells = icon.cells.map((c) =>
    [cellName(c.variant, c.weight), parseSvg(c.svg).children.map((n) => [n.tag, n.attrs]) as IconNode] as [string, IconNode]);
  return {
    slug: meta.slug,
    name: toComponentName(meta.slug),
    aliases: meta.aliases,
    deprecated: meta.deprecated !== null,
    cells,
    variants: [...new Set(icon.cells.map((c) => c.variant))],
  };
}).sort((a, b) => a.slug.localeCompare(b.slug));

const nodesLiteral = (nodes: IconNode) =>
  "[" + nodes.map(([tag, attrs]) =>
    `["${tag}",{${Object.entries(attrs).map(([k, v]) => `"${k}":"${v}"`).join(",")}}]`
  ).join(",") + "]";

const cellsLiteral = (b: Built) =>
  "{\n" + b.cells.map(([key, nodes]) => `  "${key}": ${nodesLiteral(nodes)},`).join("\n") + "\n}";

/** Narrowed to the variants an icon actually has, so asking for one it lacks is a
 *  compile error rather than a silent fallback. */
const variantUnion = (b: Built) => b.variants.map((v) => `"${v}"`).join(" | ");

const BANNER = "// Generated by scripts/generate/components.ts — do not edit.\n";

/**
 * The file a component is written to, which is its slug except when its slug is the barrel's
 * own name.
 *
 * `index` is a real concept — what is where, so you can find it — and it is also what every
 * directory in JavaScript calls its entry point. Left alone, the barrel re-exports `Index`
 * from `./index`, which is itself, and TypeScript reports a circular import alias rather
 * than anything that names the cause. The slug, the component and the published name are
 * untouched; only the file on disk moves.
 */
const RESERVED = new Set(["index"]);
const fileOf = (slug: string) => (RESERVED.has(slug) ? `${slug}-icon` : slug);

interface Target { dir: string; ext: string; render: (b: Built) => string }

const react: Target = {
  dir: fromRoot("packages/react/src/generated"),
  ext: "tsx",
  render: (b) =>
    `${BANNER}import { createIcon } from "../create-icon";\n\n` +
    `export const ${b.name} = createIcon<${variantUnion(b)}>("${b.name}", ${cellsLiteral(b)});\n` +
    b.aliases.map((a) => `\n/** @deprecated use \`${b.name}\` */\nexport const ${toComponentName(a)} = ${b.name};\n`).join(""),
};

const vue: Target = {
  dir: fromRoot("packages/vue/src/generated"),
  ext: "ts",
  render: (b) =>
    `${BANNER}import { createIcon } from "../create-icon";\n\n` +
    `export const ${b.name} = createIcon<${variantUnion(b)}>("${b.name}", ${cellsLiteral(b)});\n` +
    b.aliases.map((a) => `\n/** @deprecated use \`${b.name}\` */\nexport const ${toComponentName(a)} = ${b.name};\n`).join(""),
};

/** The generated file is framework-agnostic — only each package's create-icon differs —
 *  so every JS framework shares one emitter shape. */
const dataTarget = (pkg: string): Target => ({
  dir: fromRoot(`packages/${pkg}/src/generated`),
  ext: "ts",
  render: (b) =>
    `${BANNER}import { createIcon } from "../create-icon";\n\n` +
    `export const ${b.name} = createIcon<${variantUnion(b)}>("${b.name}", ${cellsLiteral(b)});\n` +
    b.aliases.map((a) => `\n/** @deprecated use \`${b.name}\` */\nexport const ${toComponentName(a)} = ${b.name};\n`).join(""),
});

// An emitter only writes when its package actually exists in the tree.
const targets = [react, vue, dataTarget("preact"), dataTarget("solid"), dataTarget("react-native")]
  .filter((t) => existsSync(t.dir.replace("/src/generated", "")));

for (const t of targets) {
  await rm(t.dir, { recursive: true, force: true });
  await mkdir(t.dir, { recursive: true });

  for (const b of built) {
    await writeFile(`${t.dir}/${fileOf(b.slug)}.${t.ext}`, t.render(b));
  }

  const barrel =
    BANNER +
    built.map((b) => `export { ${b.name}${b.aliases.map((a) => `, ${toComponentName(a)}`).join("")} } from "./${fileOf(b.slug)}";`).join("\n") +
    "\n\n/** Every icon slug, as a union. */\nexport type IconName =\n" +
    (built.length ? built.map((b) => `  | "${b.slug}"`).join("\n") : "  never") + ";\n";
  await writeFile(`${t.dir}/index.${t.ext === "tsx" ? "ts" : "ts"}`, barrel);

  console.log(`${t.dir} — ${built.length} components + barrel`);
}

if (!targets.length) console.log("No framework packages present yet; nothing generated.");

/**
 * Svelte ships source: one .svelte per icon delegating to a single Icon.svelte runtime,
 * with the cell data in a plain .js module beside it so consumers' bundlers compile the
 * component and tree-shake the data without this repo shipping a compiler.
 */
const svelteDir = fromRoot("packages/svelte/src/generated");
if (existsSync(svelteDir.replace("/src/generated", ""))) {
  await rm(svelteDir, { recursive: true, force: true });
  await mkdir(svelteDir, { recursive: true });
  for (const b of built) {
    await writeFile(`${svelteDir}/${fileOf(b.slug)}.data.js`,
      `${BANNER}export const cells = ${cellsLiteral(b)};\n`);
    await writeFile(`${svelteDir}/${fileOf(b.slug)}.svelte`,
      `<!-- Generated by scripts/generate/components.ts — do not edit. -->\n` +
      `<script>\n  import Icon from "../Icon.svelte";\n  import { cells } from "./${fileOf(b.slug)}.data.js";\n</script>\n\n` +
      `<Icon {cells} {...$$restProps}><slot /></Icon>\n`);
  }
  const names = (b: Built) => [b.name, ...b.aliases.map(toComponentName)];
  await writeFile(`${svelteDir}/index.js`,
    BANNER + built.map((b) =>
      names(b).map((n) => `export { default as ${n} } from "./${fileOf(b.slug)}.svelte";`).join("\n")
    ).join("\n") + "\n");
  await writeFile(`${svelteDir}/index.d.ts`,
    BANNER +
    `import type { IconComponent, Variant } from "../types";\n\n` +
    built.map((b) =>
      names(b).map((n) => `export declare const ${n}: IconComponent<${variantUnion(b)}>;`).join("\n")
    ).join("\n") + "\n\n/** Every icon slug, as a union. */\nexport type IconName =\n" +
    built.map((b) => `  | "${b.slug}"`).join("\n") + ";\n");
  console.log(`${svelteDir} — ${built.length} components + data + barrel`);
}

/** Astro ships source too: one .astro per icon over a single Icon.astro runtime. */
const astroDir = fromRoot("packages/astro/src/generated");
if (existsSync(astroDir.replace("/src/generated", ""))) {
  await rm(astroDir, { recursive: true, force: true });
  await mkdir(astroDir, { recursive: true });
  for (const b of built) {
    await writeFile(`${astroDir}/${fileOf(b.slug)}.data.js`,
      `${BANNER}export const cells = ${cellsLiteral(b)};\n`);
    await writeFile(`${astroDir}/${fileOf(b.slug)}.astro`,
      `---\n// Generated by scripts/generate/components.ts — do not edit.\nimport Icon from "../Icon.astro";\nimport { cells } from "./${fileOf(b.slug)}.data.js";\n---\n\n<Icon {...Astro.props} cells={cells}><slot /></Icon>\n`);
  }
  const names = (b: Built) => [b.name, ...b.aliases.map(toComponentName)];
  await writeFile(`${astroDir}/index.js`,
    BANNER + built.map((b) =>
      names(b).map((n) => `export { default as ${n} } from "./${fileOf(b.slug)}.astro";`).join("\n")
    ).join("\n") + "\n");
  await writeFile(`${astroDir}/index.d.ts`,
    BANNER +
    `import type { IconComponent, Variant } from "../types";\n\n` +
    built.map((b) =>
      names(b).map((n) => `export declare const ${n}: IconComponent<${variantUnion(b)}>;`).join("\n")
    ).join("\n") + "\n\n/** Every icon slug, as a union. */\nexport type IconName =\n" +
    built.map((b) => `  | "${b.slug}"`).join("\n") + ";\n");
  console.log(`${astroDir} — ${built.length} components + data + barrel`);
}

/**
 * Laravel via Blade Icons: no components to generate, just the SVGs laid out the way
 * blade-icons expects — flat names, the outline-regular cell as the bare name and every
 * other cell as a suffix.
 */
const bladeDir = fromRoot("packages/blade/resources/svg");
if (existsSync(bladeDir.replace("/resources/svg", ""))) {
  await rm(bladeDir, { recursive: true, force: true });
  await mkdir(bladeDir, { recursive: true });
  const { copyFile } = await import("node:fs/promises");
  let n = 0;
  for (const icon of icons) {
    for (const c of icon.cells) {
      const key = cellName(c.variant, c.weight);
      const name =
        key === "outline-regular" ? icon.slug :
        key === "duotone-regular" ? `${icon.slug}-duotone` :
        `${icon.slug}-${key}`;
      await writeFile(`${bladeDir}/${name}.svg`, c.svg);
      n++;
    }
  }
  console.log(`${bladeDir} — ${n} svgs for blade-icons`);
}
