/**
 * Emits packages/icons/dist/index.js — the entry `exports["."]` points at.
 *
 * The metadata is inlined as a JS object rather than re-exported from the JSON file:
 * import attributes are still awkward across bundlers and Node versions, and a package
 * entry is the wrong place to make a consumer deal with that.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fromRoot } from "../lib/fs.ts";

const OUT = fromRoot("packages/icons/dist");
const metadata = JSON.parse(await readFile(`${OUT}/metadata.json`, "utf8"));

const js = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export const metadata = ${JSON.stringify(metadata)};
export const version = metadata.version;
export const icons = metadata.icons;
export const categories = metadata.categories;

const bySlug = new Map(icons.map((i) => [i.slug, i]));
for (const i of icons) for (const a of i.aliases ?? []) bySlug.set(a, i);

/** Look up one icon by slug or alias. */
export const getIcon = (slug) => bySlug.get(slug);
/** Every icon in one category. */
export const iconsIn = (category) => icons.filter((i) => i.category === category);
`;

const dts = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export interface IconMeta {
  slug: string; name: string; category: string; subcategory: string;
  description: string; tags: string[]; aliases: string[]; keywords: string[];
  contributors: string[]; deprecated: { since: string; replacedBy?: string; reason: string } | null;
  componentName: string; contentHash: string; structuralHash: string;
  elementCount: number; byteSize: number; related: string[];
  addedIn: string; updatedIn: string;
}
export interface Category {
  slug: string; name: string; count: number;
  subcategories: { slug: string; count: number }[];
}
export interface Metadata {
  version: string; generatedAt: string;
  counts: { total: number; byCategory: Record<string, number> };
  categories: Category[]; icons: IconMeta[];
}
export declare const metadata: Metadata;
export declare const version: string;
export declare const icons: IconMeta[];
export declare const categories: Category[];
export declare const getIcon: (slug: string) => IconMeta | undefined;
export declare const iconsIn: (category: string) => IconMeta[];
`;

await mkdir(OUT, { recursive: true });
await writeFile(`${OUT}/index.js`, js);
await writeFile(`${OUT}/index.d.ts`, dts);
console.log(`index.js — ${metadata.icons.length} icons inlined, ${(js.length / 1024).toFixed(1)} KB`);
