/**
 * Emits the two entries of @iconmind/icons:
 *
 *   dist/index.js     — `exports["."]`: version and counts, a few hundred bytes.
 *   dist/metadata.js  — `exports["./metadata"]`: the full database — every icon's
 *                       description, tags, keywords, aliases — plus the lookup helpers.
 *
 * They used to be one file, and Bundlephobia read it as a 178 KB gzip package: the
 * database is a single object, so a web app importing one helper shipped all of it.
 * The database is for tools — the docs site, the MCP server, build scripts — and tools
 * can write `/metadata`; the bare package name has to cost nothing.
 *
 * The metadata is inlined as a JS object rather than re-exported from the JSON file:
 * import attributes are still awkward across bundlers and Node versions, and a package
 * entry is the wrong place to make a consumer deal with that.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fromRoot } from "../lib/fs.ts";

const OUT = fromRoot("packages/icons/dist");
const metadata = JSON.parse(await readFile(`${OUT}/metadata.json`, "utf8"));

const index = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export const version = ${JSON.stringify(metadata.version)};
export const counts = ${JSON.stringify(metadata.counts)};
// The full database — descriptions, tags, keywords, lookups — lives one import away:
//   import { getIcon, icons } from "@iconmind/icons/metadata";
`;

const indexDts = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export declare const version: string;
export declare const counts: { total: number; byCategory: Record<string, number> };
`;

const meta = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export const metadata = ${JSON.stringify(metadata)};
export const version = metadata.version;
export const icons = metadata.icons;
export const categories = metadata.categories;

const bySlug = new Map(icons.map((i) => [i.slug, i]));
for (const i of icons) for (const a of i.aliases ?? []) bySlug.set(a, i);

/** Look up one icon by slug or alias. */
export const getIcon = (slug) => bySlug.get(slug);
/** Every icon in one category. */
export const iconsIn = (category) => icons.filter((i) => i.category === category);
`;

const metaDts = `// Generated by scripts/generate/icons-entry.ts — do not edit.
export interface IconMeta {
  slug: string; name: string; category: string; subcategory: string;
  description: string; tags: string[]; aliases: string[]; keywords: string[];
  contributors: string[]; deprecated: { since: string; replacedBy?: string; reason: string } | null;
  componentName: string; contentHash: string; structuralHash: string;
  elementCount: number; byteSize: number; related: string[];
  addedIn: string; updatedIn: string;
}
export interface Category {
  slug: string; name: string; count: number;
  subcategories: { slug: string; count: number }[];
}
export interface Metadata {
  version: string; generatedAt: string;
  counts: { total: number; byCategory: Record<string, number> };
  categories: Category[]; icons: IconMeta[];
}
export declare const metadata: Metadata;
export declare const version: string;
export declare const icons: IconMeta[];
export declare const categories: Category[];
export declare const getIcon: (slug: string) => IconMeta | undefined;
export declare const iconsIn: (category: string) => IconMeta[];
`;

await mkdir(OUT, { recursive: true });
await writeFile(`${OUT}/index.js`, index);
await writeFile(`${OUT}/index.d.ts`, indexDts);
await writeFile(`${OUT}/metadata.js`, meta);
await writeFile(`${OUT}/metadata.d.ts`, metaDts);
console.log(
  `index.js — ${(index.length / 1024).toFixed(1)} KB · metadata.js — ${metadata.icons.length} icons, ${(meta.length / 1024).toFixed(1)} KB`,
);
