# -*- coding: utf-8 -*-
"""Sumber data katalog icon IconMind. Jalankan gen_catalog.py untuk merender 02b.

Deskripsi WAJIB berbahasa Inggris (CANON C11) — nilai ini menjadi field `description`
di metadata icon dan isi GitHub issue untuk kontributor global.
"""

# (P1, P2 kumulatif, P3 kumulatif) — harus cocok dengan tabel 2.6 di 02-icon-taxonomy.md
THRESHOLDS = {
    "ai": (20, 45, 75), "agents": (16, 40, 65), "mcp": (10, 25, 40), "rag": (10, 28, 45),
    "data": (6, 22, 40), "devops": (6, 24, 42), "cloud": (4, 18, 33), "security": (4, 18, 33),
    "automation": (4, 18, 30), "analytics": (4, 15, 27), "devtools": (6, 24, 40), "interface": (10, 23, 30),
}

DOMAIN_TITLE = {
    "ai": "AI & LLM", "agents": "Agents", "mcp": "MCP", "rag": "RAG & Search",
    "data": "Data Engineering", "devops": "DevOps", "cloud": "Cloud", "security": "Security",
    "automation": "Automation", "analytics": "Analytics", "devtools": "Developer Tools", "interface": "Interface",
}

SUBCAT_ORDER = {
    "ai": ["model","inference","prompt","token","context","embedding","training","evaluation","safety","multimodal"],
    "agents": ["agent-core","multi-agent","planning","execution","reflection","memory","tool-use","communication","lifecycle"],
    "mcp": ["server","client","resource","tool","prompt","transport","sampling","registry"],
    "rag": ["ingestion","chunking","retrieval","ranking","vector","knowledge","grounding"],
    "data": ["pipeline","transform","storage","streaming","quality","catalog","orchestration"],
    "devops": ["ci-cd","container","orchestration","infrastructure","observability","incident","release"],
    "cloud": ["compute","storage","network","serverless","edge","region","cost"],
    "security": ["auth","secret","encryption","policy","threat","compliance","ai-security"],
    "automation": ["workflow","trigger","condition","action","schedule","integration","human-loop"],
    "analytics": ["chart","metric","dashboard","segment","experiment","llm-observability"],
    "devtools": ["code","terminal","version-control","package","debug","api","testing","editor"],
    "interface": ["arrow","action","state","layout","media","file","time","communication"],
}

# Urutan = prioritas. Posisi menentukan phase.
ICONS = {}

ICONS["ai"] = [
 ("model","model","Generic AI model"),("llm","model","Large language model"),
 ("prompt","prompt","Instruction given to a model"),("token","token","Smallest unit of text"),
 ("context-window","context","Span of tokens a model can see"),("embedding","embedding","Vector representation of text"),
 ("inference","inference","Running a model to produce output"),("training","training","Training a model"),
 ("fine-tuning","training","Adapting a model to a domain"),("evaluation","evaluation","Measuring model quality"),
 ("guardrail","safety","Constraint placed on model output"),("hallucination","evaluation","Confidently wrong model output"),
 ("dataset","training","Collection of training data"),("benchmark","evaluation","Performance benchmark"),
 ("tokenizer","token","Splits text into tokens"),("vector","embedding","Numeric vector"),
 ("multimodal","multimodal","Model spanning several modalities"),("chain-of-thought","prompt","Step-by-step reasoning"),
 ("system-prompt","prompt","System-level instruction"),("temperature","inference","Randomness parameter for output"),
 ("prompt-template","prompt","Parameterised prompt template"),("prompt-chain","prompt","Chain of sequential prompts"),
 ("few-shot","prompt","Prompt that includes examples"),("zero-shot","prompt","Prompt with no examples"),
 ("user-prompt","prompt","Input written by the user"),("token-count","token","Token count"),
 ("token-limit","token","Token limit"),("token-cost","token","Cost per token"),
 ("context-full","context","Context window at capacity"),("context-compress","context","Compressing the context"),
 ("embedding-model","embedding","Model that produces embeddings"),("similarity","embedding","Similarity between vectors"),
 ("model-add","model","Add a model"),("model-check","model","Model validated"),
 ("model-alert","model","Alert raised on a model"),("model-off","model","Model disabled"),
 ("model-deploy","model","Deploying a model to production"),("streaming-response","inference","Response streamed token by token"),
 ("latency","inference","Response latency"),("throughput","inference","Throughput per second"),
 ("checkpoint","training","Training checkpoint"),("epoch","training","One training epoch"),
 ("loss-curve","training","Training loss curve"),("quantization","training","Reducing model weight precision"),
 ("lora","training","Lightweight training adapter"),("foundation-model","model","Large-scale foundation model"),
 ("base-model","model","Base model before tuning"),("instruct-model","model","Instruction-tuned model"),
 ("reasoning-model","model","Reasoning model"),("small-language-model","model","Small language model"),
 ("llm-chat","model","Chat interface to a model"),("model-swap","model","Swap one model for another"),
 ("model-download","model","Download model weights"),("inference-fast","inference","Low-latency inference"),
 ("inference-batch","inference","Batched inference"),("cold-start","inference","Cold start"),
 ("prompt-library","prompt","Library of saved prompts"),("context-overflow","context","Context window overflowed"),
 ("dimension","embedding","Vector dimensionality"),("cosine-distance","embedding","Cosine distance"),
 ("training-data","training","Training data"),("gradient","training","Optimisation gradient"),
 ("distillation","training","Distilling a model into a smaller one"),("pruning","training","Pruning model weights"),
 ("eval-suite","evaluation","Suite of evaluations"),("score-card","evaluation","Scorecard of results"),
 ("human-eval","evaluation","Human evaluation"),("drift","evaluation","Model behaviour drifting over time"),
 ("content-filter","safety","Content filter"),("safety-check","safety","Safety check"),
 ("alignment","safety","Aligning a model to intended values"),("red-team","safety","Adversarial red-team testing"),
 ("refusal","safety","Model refusing to answer"),("bias-check","safety","Bias check"),
 ("vision-model","multimodal","Vision model"),("audio-model","multimodal","Audio model"),
 ("image-generation","multimodal","Image generation"),("speech-to-text","multimodal","Speech to text"),
 ("text-to-speech","multimodal","Text to speech"),
]

ICONS["agents"] = [
 ("agent","agent-core","Autonomous agent"),("multi-agent","multi-agent","Several agents working together"),
 ("agent-run","lifecycle","Start an agent"),("agent-stop","lifecycle","Stop an agent"),
 ("planner","planning","Component that builds the plan"),("plan","planning","Plan of work"),
 ("executor","execution","Component that carries out steps"),("supervisor","multi-agent","Agent that supervises others"),
 ("memory","memory","Memory an agent writes to and reads back"),("tool-calling","tool-use","Invoking a tool"),
 ("reflection","reflection","Agent evaluating its own output"),("goal","planning","Goal an agent works toward"),
 ("subtask","planning","Subtask"),("agent-thinking","lifecycle","Agent is thinking"),
 ("human-approval","communication","Human approval"),("agent-log","lifecycle","Log of agent activity"),
 ("agent-add","agent-core","Add an agent"),("agent-remove","agent-core","Remove an agent"),
 ("agent-check","agent-core","Agent validated"),("agent-alert","agent-core","Alert raised on an agent"),
 ("agent-off","agent-core","Agent disabled"),("agent-config","agent-core","Agent configuration"),
 ("agent-pause","lifecycle","Pause an agent"),("agent-state","lifecycle","Agent state"),
 ("agent-idle","lifecycle","Agent is idle"),("agent-working","lifecycle","Agent is working"),
 ("agent-blocked","lifecycle","Agent is blocked"),("agent-done","lifecycle","Agent has finished"),
 ("orchestrator","multi-agent","Coordinator of multiple agents"),("agent-handoff","multi-agent","Handoff between agents"),
 ("agent-delegate","multi-agent","Delegating a task"),("agent-team","multi-agent","Team of agents"),
 ("task-graph","planning","Graph of task dependencies"),("decompose","planning","Breaking a task into parts"),
 ("action-step","execution","Action step"),("retry","execution","Retry"),
 ("fallback","execution","Fallback path"),("memory-short-term","memory","Short-term memory"),
 ("memory-long-term","memory","Long-term memory"),("tool-registry","tool-use","Registry of available tools"),
 ("tool-result","tool-use","Result returned by a tool"),("tool-error","tool-use","Tool call error"),
 ("function-call","tool-use","Structured function invocation"),("tool-permission","tool-use","Permission to use a tool"),
 ("agent-message","communication","Message between agents"),("agent-broadcast","communication","Broadcast to every agent"),
 ("agent-inbox","communication","Agent inbox"),("self-critique","reflection","Agent critiquing its own work"),
 ("self-correct","reflection","Agent correcting itself"),("verify-step","reflection","Verifying a step"),
 ("agent-swarm","multi-agent","Swarm of agents"),("agent-hierarchy","multi-agent","Agents arranged in tiers"),
 ("router-agent","multi-agent","Agent that routes work"),("worker-agent","multi-agent","Worker agent"),
 ("strategy","planning","Strategy for solving a task"),("objective","planning","Measurable objective"),
 ("loop-step","execution","Looping step"),("branch-step","execution","Branching step"),
 ("timeout","execution","Step timeout"),("memory-episodic","memory","Episodic memory"),
 ("memory-semantic","memory","Semantic memory"),("memory-write","memory","Write to memory"),
 ("memory-read","memory","Read from memory"),("memory-clear","memory","Clear memory"),
 ("scratchpad","memory","Temporary working notes"),("agent-protocol","communication","Protocol between agents"),
 ("agent-negotiation","communication","Negotiation between agents"),("evaluate-step","reflection","Scoring a step"),
 ("execute","execution","Executing a step"),("agent-sandbox","execution","Isolated environment for an agent"),
]

ICONS["mcp"] = [
 ("mcp","server","Model Context Protocol"),("mcp-server","server","MCP server"),
 ("mcp-client","client","MCP client"),("mcp-resource","resource","Data an MCP server exposes"),
 ("mcp-tool","tool","Capability an MCP server exposes"),("mcp-prompt","prompt","Prompt template an MCP server exposes"),
 ("mcp-connection","client","MCP connection"),("mcp-tool-call","tool","Calling an MCP tool"),
 ("mcp-capability","transport","Negotiated capability"),("mcp-config","registry","MCP configuration"),
 ("mcp-server-add","server","Add an MCP server"),("mcp-server-check","server","MCP server validated"),
 ("mcp-server-alert","server","Alert on an MCP server"),("mcp-server-off","server","MCP server disabled"),
 ("mcp-handshake","client","Protocol handshake"),("mcp-resource-list","resource","List of resources"),
 ("mcp-resource-read","resource","Read a resource"),("mcp-resource-add","resource","Add a resource"),
 ("mcp-tool-result","tool","Result from an MCP tool"),("mcp-tool-error","tool","MCP tool error"),
 ("mcp-tool-schema","tool","Tool input schema"),("mcp-prompt-list","prompt","List of prompts"),
 ("mcp-transport","transport","Transport layer"),("mcp-stdio","transport","Stdio transport"),
 ("mcp-http","transport","HTTP transport"),("mcp-sse","transport","Server-sent events transport"),
 ("mcp-websocket","transport","WebSocket transport"),("mcp-session","transport","MCP session"),
 ("mcp-initialize","transport","Session initialisation"),("mcp-notification","transport","Protocol notification"),
 ("mcp-sampling","sampling","Sampling request sent to the client"),("mcp-completion","sampling","Argument completion"),
 ("mcp-progress","sampling","Operation progress"),("mcp-cancel","sampling","Operation cancelled"),
 ("mcp-root","resource","Exposed root directory"),("mcp-resource-template","resource","Resource URI template"),
 ("mcp-resource-subscribe","resource","Subscription to changes"),("mcp-tool-add","tool","Add a tool"),
 ("mcp-tool-permission","tool","Tool permission"),("mcp-prompt-add","prompt","Add a prompt"),
 ("mcp-prompt-argument","prompt","Prompt argument"),("mcp-registry","registry","Directory of MCP servers"),
 ("mcp-manifest","registry","Server manifest"),("mcp-inspector","registry","MCP inspection tool"),
 ("mcp-logging","sampling","Protocol log"),
]

ICONS["rag"] = [
 ("rag-pipeline","grounding","End-to-end RAG pipeline"),("retriever","retrieval","Component that retrieves documents"),
 ("chunk","chunking","Chunk of a document"),("vector-database","vector","Database for storing and searching vectors"),
 ("semantic-search","retrieval","Semantic search"),("vector-search","retrieval","Vector search"),
 ("reranker","ranking","Model that reorders results by relevance"),("knowledge-base","knowledge","Knowledge base"),
 ("document","ingestion","Source document"),("source-citation","grounding","Citation of a source"),
 ("ingestion","ingestion","Ingesting data into the system"),("loader","ingestion","Document loader"),
 ("document-parse","ingestion","Parsing a document"),("document-split","ingestion","Splitting a document"),
 ("chunk-overlap","chunking","Content shared between consecutive chunks"),("chunk-size","chunking","Chunk size"),
 ("semantic-chunk","chunking","Chunking by meaning"),("hybrid-search","retrieval","Hybrid keyword and vector search"),
 ("keyword-search","retrieval","Keyword search"),("similarity-search","retrieval","Similarity search"),
 ("top-k","retrieval","Take the top k results"),("rerank","ranking","Reordering results"),
 ("relevance-score","ranking","Relevance score"),("vector-index","vector","Vector index"),
 ("vector-query","vector","Vector query"),("vector-upsert","vector","Insert or update a vector"),
 ("knowledge-graph","knowledge","Knowledge graph"),("grounding","grounding","Grounding an answer in sources"),
 ("crawler","ingestion","Content crawler"),("extractor","ingestion","Data extractor"),
 ("ocr","ingestion","Optical character recognition"),("ingestion-pipeline","ingestion","Ingestion pipeline"),
 ("document-add","ingestion","Add a document"),("chunk-add","chunking","Add a chunk"),
 ("chunk-strategy","chunking","Chunking strategy"),("recursive-split","chunking","Recursive splitting"),
 ("recall","retrieval","Recall of relevant results"),("precision","retrieval","Precision of results"),
 ("cross-encoder","ranking","Cross-encoder that ranks pairs"),("mmr","ranking","Maximal marginal relevance"),
 ("filter-result","ranking","Filtering results"),("hnsw","vector","Hierarchical navigable small world index"),
 ("namespace","vector","Vector namespace"),("collection","vector","Collection of vectors"),
 ("document-store","knowledge","Document store"),("corpus","knowledge","Text corpus"),
 ("citation-link","grounding","Link to a cited source"),("context-injection","grounding","Injecting retrieved context"),
 ("content-freshness","knowledge","How recent the content is"),("answer-synthesis","grounding","Synthesising an answer from sources"),
]

ICONS["data"] = [
 ("pipeline","pipeline","Data processing pipeline"),("etl","pipeline","Extract, transform, load"),
 ("data-warehouse","storage","Data warehouse"),("stream","streaming","Stream of data"),
 ("data-quality","quality","Data quality"),("dag","orchestration","Directed acyclic graph of tasks"),
 ("pipeline-run","pipeline","Pipeline run"),("pipeline-fail","pipeline","Pipeline failed"),
 ("elt","pipeline","Extract, load, transform"),("batch-job","pipeline","Batch job"),
 ("transform","transform","Data transformation"),("aggregate","transform","Aggregating data"),
 ("join-data","transform","Joining data"),("deduplicate","transform","Removing duplicates"),
 ("data-lake","storage","Data lake"),("table","storage","Data table"),
 ("schema","storage","Data schema"),("event-stream","streaming","Event stream"),
 ("message-queue","streaming","Message queue"),("data-validation","quality","Data validation"),
 ("lineage","catalog","Data lineage"),("data-catalog","catalog","Data catalog"),
 ("stream-job","pipeline","Streaming job"),("task-node","orchestration","Task node"),
 ("map-step","transform","Map step"),("filter-step","transform","Filter step"),
 ("normalize","transform","Normalising data"),("enrich","transform","Enriching data"),
 ("schema-map","transform","Schema mapping"),("lakehouse","storage","Lakehouse"),
 ("partition","storage","Table partition"),("column","storage","Table column"),
 ("row","storage","Table row"),("index-data","storage","Data index"),
 ("topic","streaming","Message topic"),("producer","streaming","Message producer"),
 ("consumer","streaming","Message consumer"),("null-check","quality","Null check"),
 ("anomaly-data","quality","Data anomaly"),("freshness-check","quality","Freshness check"),
 ("offset","streaming","Stream read offset"),("backpressure","streaming","Backpressure in a stream"),
 ("data-contract","quality","Data contract"),("metadata-store","catalog","Metadata store"),
 ("data-owner","catalog","Data owner"),("data-tag","catalog","Data tag"),
 ("governance","catalog","Data governance"),
]

ICONS["devops"] = [
 ("build","ci-cd","Build process"),("deploy","ci-cd","Deploying an application"),
 ("container","container","Container"),("cluster","orchestration","Cluster"),
 ("observability","observability","System observability"),("incident","incident","Production incident"),
 ("build-fail","ci-cd","Build failed"),("build-pass","ci-cd","Build passed"),
 ("pipeline-ci","ci-cd","Continuous integration pipeline"),("artifact","release","Build artifact"),
 ("deploy-rollback","release","Rolling back a deployment"),("release-tag","release","Release tag"),
 ("container-image","container","Container image"),("container-run","container","Run a container"),
 ("container-stop","container","Stop a container"),("registry-image","container","Image registry"),
 ("pod","orchestration","Pod"),("replica","orchestration","Replica"),
 ("autoscale","orchestration","Autoscaling"),("load-balancer","orchestration","Load balancer"),
 ("log-stream","observability","Log stream"),("trace-span","observability","Trace span"),
 ("metric-point","observability","Metric data point"),("alert-rule","observability","Alerting rule"),
 ("health-check","observability","Health check"),("on-call","incident","On-call rotation"),
 ("environment","infrastructure","Deployment environment"),("infrastructure","infrastructure","Infrastructure"),
 ("infra-plan","infrastructure","Planned infrastructure change"),("provision","infrastructure","Provisioning resources"),
 ("config-drift","infrastructure","Configuration drift"),("blue-green","release","Blue-green release"),
 ("canary","release","Canary release"),("cache-build","ci-cd","Build cache"),
 ("layer","container","Image layer"),("volume","container","Data volume"),
 ("container-file","container","Container definition file"),("node-cluster","orchestration","Cluster node"),
 ("service-mesh","orchestration","Service mesh"),("ingress","orchestration","Cluster ingress"),
 ("namespace-cluster","orchestration","Cluster namespace"),("uptime","observability","Uptime"),
 ("dashboard-ops","observability","Operations dashboard"),("postmortem","incident","Post-incident review"),
 ("runbook","incident","Incident runbook"),("rollback","incident","Rolling back to a known state"),
 ("sla","incident","Service level agreement"),
]

ICONS["cloud"] = [
 ("cloud","compute","Cloud"),("serverless","serverless","Serverless"),
 ("storage-bucket","storage","Storage bucket"),("gpu","compute","Graphics processing unit"),
 ("instance","compute","Compute instance"),("vm","compute","Virtual machine"),
 ("cpu","compute","Central processing unit"),("gpu-cluster","compute","GPU cluster"),
 ("object-store","storage","Object storage"),("block-storage","storage","Block storage"),
 ("backup","storage","Backup"),("snapshot","storage","Volume snapshot"),
 ("network","network","Network"),("firewall-cloud","network","Network firewall"),
 ("gateway","network","Network gateway"),("cdn","storage","Content delivery network"),
 ("function-cloud","serverless","Serverless function"),("region","region","Region"),
 ("edge-node","edge","Edge node"),("edge-function","edge","Edge function"),
 ("availability-zone","region","Availability zone"),("cost-cloud","cost","Cloud cost"),
 ("budget-alert","cost","Budget alert"),("cloud-add","compute","Add a cloud resource"),
 ("cloud-check","compute","Cloud resource validated"),("cloud-alert","compute","Cloud alert"),
 ("cloud-off","compute","Cloud resource disabled"),("multi-cloud","compute","Multiple cloud providers"),
 ("hybrid-cloud","compute","Hybrid cloud"),("private-cloud","compute","Private cloud"),
 ("bare-metal","compute","Bare-metal server"),("memory-ram","compute","Working memory"),
 ("tpu","compute","Tensor processing unit"),("file-storage","storage","File storage"),
 ("archive","storage","Cold archive"),("vpc","network","Virtual private cloud"),
 ("subnet","network","Subnet"),("dns","network","Domain name system"),
 ("private-link","network","Private link"),("egress","network","Egress traffic"),
 ("cold-boot","serverless","Function cold boot"),("replication-geo","region","Cross-region replication"),
 ("usage-quota","cost","Usage quota"),("edge-cache","edge","Edge cache"),
]

ICONS["security"] = [
 ("auth","auth","Authentication"),("secret","secret","Application secret"),
 ("encryption","encryption","Encryption"),("prompt-injection","ai-security","Prompt injection"),
 ("login","auth","Sign in"),("logout","auth","Sign out"),
 ("mfa","auth","Multi-factor authentication"),("api-key","auth","API key"),
 ("session-token","auth","Session token"),("secret-vault","secret","Secret vault"),
 ("secret-rotate","secret","Rotating a secret"),("certificate","secret","Certificate"),
 ("encrypt","encryption","Encrypt"),("decrypt","encryption","Decrypt"),
 ("permission","policy","Access permission"),("audit-log","policy","Audit log"),
 ("vulnerability","threat","Vulnerability"),("jailbreak","ai-security","Jailbreaking a model's guardrails"),
 ("sso","auth","Single sign-on"),("oauth","auth","Delegated authorisation"),
 ("passkey","auth","Passkey"),("service-account","auth","Service account"),
 ("secret-leak","secret","Leaked secret"),("credential","secret","Credential"),
 ("key-pair","encryption","Key pair"),("hash","encryption","Hash value"),
 ("signature","encryption","Digital signature"),("rbac","policy","Role-based access control"),
 ("role","policy","Role"),("access-grant","policy","Granting access"),
 ("access-deny","policy","Denying access"),("threat","threat","Threat"),
 ("pii-redaction","ai-security","Redacting personal data"),("policy","policy","Security policy"),
 ("tls","encryption","Transport layer security"),("end-to-end","encryption","End-to-end encryption"),
 ("compliance","compliance","Compliance"),("compliance-report","compliance","Compliance report"),
 ("cve","threat","Catalogued vulnerability"),("malware","threat","Malware"),
 ("intrusion","threat","Intrusion"),("firewall","threat","Firewall"),
 ("ddos","threat","Denial-of-service attack"),("patch","threat","Security patch"),
 ("data-exfiltration","ai-security","Data exfiltration"),("model-poisoning","ai-security","Poisoning a model's training data"),
 ("output-sanitize","ai-security","Sanitising model output"),("llm-firewall","ai-security","Firewall for model traffic"),
]

ICONS["automation"] = [
 ("workflow","workflow","Workflow"),("trigger","trigger","Trigger"),
 ("action","action","Action"),("condition","condition","Condition"),
 ("workflow-run","workflow","Run a workflow"),("workflow-add","workflow","Add a workflow"),
 ("workflow-pause","workflow","Pause a workflow"),("workflow-stop","workflow","Stop a workflow"),
 ("workflow-fail","workflow","Workflow run failed"),("trigger-webhook","trigger","Webhook trigger"),
 ("trigger-schedule","trigger","Scheduled trigger"),("trigger-event","trigger","Event trigger"),
 ("branch","condition","Branch"),("loop","condition","Loop"),
 ("delay","condition","Delay"),("schedule","schedule","Schedule"),
 ("integration","integration","Integration"),("human-in-the-loop","human-loop","Human in the loop"),
 ("workflow-template","workflow","Workflow template"),("trigger-manual","trigger","Manual trigger"),
 ("trigger-file","trigger","File trigger"),("switch-case","condition","Switch between several paths"),
 ("wait-approval","human-loop","Waiting for approval"),("retry-policy","condition","Retry policy"),
 ("error-handler","condition","Error handler"),("action-http","action","HTTP request action"),
 ("action-email","action","Send email action"),("action-notify","action","Notification action"),
 ("cron","schedule","Cron schedule"),("connector","integration","Connector"),
 ("action-script","action","Run script action"),("action-database","action","Database action"),
 ("recurring","schedule","Recurring"),("calendar-run","schedule","Runs on a calendar"),
 ("webhook","integration","Webhook"),("api-bridge","integration","API bridge"),
 ("sync-two-way","integration","Two-way sync"),("approval-step","human-loop","Approval step"),
]

ICONS["analytics"] = [
 ("chart-line","chart","Line chart"),("chart-bar","chart","Bar chart"),
 ("dashboard","dashboard","Dashboard"),("metric","metric","Metric"),
 ("chart-area","chart","Area chart"),("chart-pie","chart","Pie chart"),
 ("kpi","metric","Key performance indicator"),("trend-up","metric","Upward trend"),
 ("trend-down","metric","Downward trend"),("report","dashboard","Report"),
 ("widget","dashboard","Dashboard widget"),("chart-funnel","chart","Funnel chart"),
 ("segment","segment","User segment"),("experiment","experiment","Experiment"),
 ("llm-trace","llm-observability","Trace of a model call"),("chart-scatter","chart","Scatter chart"),
 ("chart-heatmap","chart","Heatmap"),("sparkline","chart","Sparkline"),
 ("counter","metric","Counter"),("gauge","metric","Gauge"),
 ("comparison","metric","Comparison"),("percentile","metric","Percentile"),
 ("export-report","dashboard","Export a report"),("filter-analytics","dashboard","Analytics filter"),
 ("date-range","dashboard","Date range"),("cohort","segment","Cohort"),
 ("token-usage","llm-observability","Token usage"),("drilldown","dashboard","Drill down into detail"),
 ("user-journey","segment","User journey"),("retention","segment","Retention"),
 ("churn","segment","Churn"),("conversion","segment","Conversion"),
 ("ab-test","experiment","A/B test"),("variant","experiment","Test variant"),
 ("significance","experiment","Statistical significance"),("feature-flag","experiment","Feature flag"),
 ("cost-per-request","llm-observability","Cost per request"),("prompt-analytics","llm-observability","Prompt analytics"),
 ("model-comparison","llm-observability","Model comparison"),
]

ICONS["devtools"] = [
 ("code","code","Code"),("terminal","terminal","Terminal"),
 ("branch-git","version-control","Repository branch"),("package","package","Package"),
 ("api","api","Application programming interface"),("debug","debug","Debugger"),
 ("code-block","code","Code block"),("code-diff","code","Code diff"),
 ("commit","version-control","Commit"),("merge","version-control","Merge"),
 ("pull-request","version-control","Pull request"),("dependency","package","Dependency"),
 ("install","package","Install"),("endpoint","api","API endpoint"),
 ("request","api","Request"),("response","api","Response"),
 ("breakpoint","debug","Breakpoint"),("stack-trace","debug","Stack trace"),
 ("test-unit","testing","Unit test"),("coverage","testing","Test coverage"),
 ("command","terminal","Command"),("shell","terminal","Shell"),
 ("snippet","code","Code snippet"),("format-code","code","Code formatting"),
 ("code-review","code","Code review"),("refactor","code","Refactor"),
 ("syntax","code","Syntax"),("script-run","terminal","Run a script"),
 ("process","terminal","Process"),("environment-var","terminal","Environment variable"),
 ("tag-git","version-control","Version tag"),("fork","version-control","Fork"),
 ("clone","version-control","Clone a repository"),("conflict","version-control","Merge conflict"),
 ("lockfile","package","Lockfile"),("version-bump","package","Version bump"),
 ("monorepo","package","Monorepo"),("workspace","package","Workspace"),
 ("step-over","debug","Step over"),("watch-variable","debug","Watch a variable"),
 ("profiler","debug","Profiler"),("memory-leak","debug","Memory leak"),
 ("status-code","api","Status code"),("rate-limit","api","Rate limit"),
 ("openapi","api","OpenAPI specification"),("graphql-node","api","GraphQL node"),
 ("test-e2e","testing","End-to-end test"),("assertion","testing","Assertion"),
 ("mock","testing","Mock"),("flaky-test","testing","Flaky test"),
 ("editor-tab","editor","Editor tab"),("editor-split","editor","Split editor pane"),
 ("autocomplete","editor","Autocomplete"),("inline-suggestion","editor","Inline suggestion"),
]

ICONS["interface"] = [
 ("check","action","Check"),("close","action","Close"),
 ("plus","action","Add"),("minus","action","Remove"),
 ("search","action","Search"),("settings","action","Settings"),
 ("chevron-right","arrow","Chevron right"),("chevron-down","arrow","Chevron down"),
 ("loading","state","Loading"),("warning","state","Warning"),
 ("arrow-up","arrow","Arrow up"),("arrow-down","arrow","Arrow down"),
 ("arrow-left","arrow","Arrow left"),("arrow-right","arrow","Arrow right"),
 ("chevron-up","arrow","Chevron up"),("chevron-left","arrow","Chevron left"),
 ("edit","action","Edit"),("trash","action","Delete"),
 ("copy","action","Copy"),("download","action","Download"),
 ("upload","action","Upload"),("filter","action","Filter"),
 ("refresh","action","Refresh"),("success","state","Success"),
 ("error","state","Error"),("info","state","Information"),
 ("sidebar","layout","Sidebar"),("grid-view","layout","Grid view"),
 ("list-view","layout","List view"),("file","file","File"),
 ("folder","file","Folder"),("link","action","Link"),
 ("user","communication","User"),("bell","communication","Notification bell"),
 ("arrow-external","arrow","External link"),("arrow-back","arrow","Back"),
 ("share","action","Share"),("sort","action","Sort"),
 ("more-horizontal","action","More options, horizontal"),("more-vertical","action","More options, vertical"),
 ("help","state","Help"),("lock-ui","state","Locked"),
 ("star","state","Star"),("bookmark","state","Bookmark"),
 ("pin","state","Pin"),("panel","layout","Panel"),
 ("expand","layout","Expand"),("collapse","layout","Collapse"),
 ("fullscreen","layout","Fullscreen"),("drag-handle","layout","Drag handle"),
 ("image","media","Image"),("video","media","Video"),
 ("audio","media","Audio"),("file-code","file","Code file"),
 ("calendar","time","Calendar"),("clock","time","Clock"),
 ("timer","time","Timer"),("users","communication","Users"),
 ("mail","communication","Email"),("message","communication","Message"),
]
