/**
 * R46 · Education: school & classroom — the building, the people in it, and everything in
 * the pencil case.
 *
 * The board and the desk carry the room; the tools each get their own outline — a pencil,
 * a pen nib, a chisel-tipped marker, a ruler, a protractor, a pair of compasses, a
 * calculator, a spiral notebook, a backpack, a lunchbox, a locker, a mortarboard.
 */
import { arc, col, disc, poly, raw, rect, row } from "../forms.ts";
import type { Icon } from "../build.ts";

const c = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({
  slug, category: "education", subcategory: "school", name, description,
  tags, aliases, keywords, family, shapes,
});

/** The board on the wall, with room for what is written on it. */
const BOARD = () => rect(2, 3, 20, 14, 2);
/** The sheet of work. */
const PAGE = () => rect(4, 3, 16, 18, 2);
/** The calendar page: a rail, two pegs and the sheet under them. */
const CAL = () => [rect(3, 5, 18, 16, 2), row(9, 3, 21), col(8, 2, 5), col(16, 2, 5)];
/** A person: the head and the shoulders under it. */
const PERSON = (x: number, y: number, r: number) => [disc(x, y, r), arc(x, y + r * 3, r * 2.2, 180, 360)];
/** The pencil, lying on the diagonal: a body, a shoulder and a point. */
const PENCIL = () => [
  poly([[7, 16], [16, 7], [19, 10], [10, 19]], true),
  poly([[7, 16], [4, 19], [10, 19]]),
  poly([[14, 9], [17, 12]]),
];

export const BATCH_133: Icon[] = [
  /* ── the place ──────────────────────────────────────────────────────────────── */
  c("school", "School", "The building with its pediment",
    ["school", "building", "primary"], [], ["school", "school building", "primary school", "secondary school"],
    "figure", [rect(3, 8, 18, 12, 2), poly([[7, 8], [12, 3], [17, 8]]), col(8, 12, 20), col(16, 12, 20)]),
  c("classroom", "Classroom", "The board at the front and a desk in front of it",
    ["classroom", "room", "class"], [], ["classroom", "class", "the room", "front of the class"],
    "figure", [rect(3, 3, 18, 10, 2), poly([[4, 21], [4, 17], [20, 17], [20, 21]])]),
  c("chalkboard", "Chalkboard", "The board with its tray",
    ["board", "chalk", "blackboard"], ["blackboard"], ["chalkboard", "blackboard", "the board", "front of class"],
    "board", [BOARD(), row(20, 5, 19), poly([[7, 9], [15, 9]]), poly([[7, 13], [12, 13]])]),
  c("whiteboard", "Whiteboard", "The board with a marker on the ledge",
    ["board", "marker", "dry-wipe"], ["dry-wipe-board"], ["whiteboard", "dry wipe board", "marker board", "the board"],
    "board", [BOARD(), row(20, 5, 19), poly([[8, 12], [14, 6], [16, 8], [10, 14]], true)]),
  c("school-desk", "Desk", "The desk with a chair pushed under it",
    ["desk", "chair", "seat"], [], ["school desk", "desk and chair", "a place to sit", "seat"],
    "desk", [row(7, 2, 16), col(4, 7, 18), col(14, 7, 18), poly([[17, 18], [17, 10], [21, 10]]), poly([[17, 14], [21, 14]])]),
  c("locker", "Locker", "The tall door with its vent",
    ["locker", "door", "store"], [], ["locker", "school locker", "store your things", "locker room"],
    "locker", [rect(6, 2, 12, 20, 2), row(6, 9, 15), row(9, 9, 15), disc(15, 14, 1)]),
  c("pin-board", "Pin board", "The board with notes pinned to it",
    ["board", "notes", "pinned"], ["notice-board"], ["pin board", "notice board", "pinned up", "notes"],
    "board", [BOARD(), poly([[6, 8], [11, 8], [11, 14], [6, 14]], true), poly([[14, 7], [19, 7], [19, 12], [14, 12]], true)]),
  c("projector", "Projector", "The box and the light going out of it",
    ["projector", "beam", "screen"], [], ["projector", "beamer", "project a slide", "beam"],
    "projector", [rect(2, 8, 12, 9, 2), disc(8, 12.5, 2), poly([[14, 9], [18, 5]]), poly([[14, 16], [18, 20]]), poly([[20, 4], [20, 21]])]),
  c("school-playground", "Playground", "The swing in the yard",
    ["playground", "swing", "yard"], ["schoolyard"], ["playground", "schoolyard", "playtime", "the yard"],
    "swing", [row(6, 4, 20), col(4, 6, 20), col(20, 6, 20), col(9, 6, 15), col(15, 6, 15), row(15, 8, 16)]),

  /* ── the people ─────────────────────────────────────────────────────────────── */
  c("teacher", "Teacher", "The one standing at the board",
    ["teacher", "class", "front"], [], ["teacher", "the teacher", "at the board", "teaching"],
    "person", [rect(10, 4, 12, 11, 2), disc(6, 9, 3), arc(6, 18, 4, 180, 360)]),
  c("student", "Student", "The one with the cap on",
    ["student", "cap", "learner"], ["learner"], ["student", "learner", "at school", "studying"],
    "person", [poly([[4, 7], [7, 4], [17, 4], [20, 7], [17, 10], [7, 10]], true), disc(12, 14, 3), arc(12, 21, 4.5, 180, 360)]),
  c("pupil", "Pupil", "The small one with a book",
    ["pupil", "child", "book"], [], ["pupil", "schoolchild", "the class", "young learner"],
    "person", [disc(8, 6, 3), arc(8, 15, 4.5, 180, 360), poly([[14, 20], [14, 12], [21, 12], [21, 20]], true), col(17.5, 12, 20)]),
  c("group-work", "Group work", "Three heads round one table",
    ["group", "together", "table"], ["teamwork"], ["group work", "working together", "in a group", "table"],
    "person", [disc(6, 9, 3), disc(12, 7, 3), disc(18, 9, 3), row(15, 2, 22), col(12, 15, 20)]),
  c("raise-hand", "Hand up", "The arm up with the hand open",
    ["hand", "up", "ask"], ["hand-up"], ["hand up", "raise your hand", "put your hand up", "ask"],
    "hand", [raw("M7 21V13A2 2 0 0 1 11 13V9A2 2 0 0 1 15 9V13A2 2 0 0 1 19 13V17", "an open hand on the end of an arm", false), poly([[15, 9], [15, 4]])]),
  c("ask-question", "Ask a question", "The hand up and the question with it",
    ["question", "ask", "hand"], [], ["ask a question", "a question", "put your hand up", "ask"],
    "bubble", [raw("M4 4H18A2 2 0 0 1 20 6V13A2 2 0 0 1 18 15H12L8 19V15H4A2 2 0 0 1 2 13V6A2 2 0 0 1 4 4Z", "a bubble with a tail", true), raw("M9 8A2.5 2.5 0 0 1 14 8C14 10 11.5 10 11.5 11.5", "the hook of a question mark", false), disc(11.5, 13, 1)]),
  c("answer", "Answer", "The bubble with the answer in it",
    ["answer", "reply", "idea"], [], ["answer", "the answer", "reply", "got it"],
    "bubble", [raw("M4 4H18A2 2 0 0 1 20 6V13A2 2 0 0 1 18 15H12L8 19V15H4A2 2 0 0 1 2 13V6A2 2 0 0 1 4 4Z", "a bubble with a tail", true), poly([[7, 10], [10, 13], [15, 8]])]),
  c("attendance", "Attendance", "The register with a tick against each name",
    ["register", "names", "roll"], ["register"], ["attendance", "register", "roll call", "who is here"],
    "page", [PAGE(), col(9, 3, 21), poly([[11, 7], [13, 9], [17, 5]]), poly([[11, 13], [13, 15], [17, 11]]), poly([[11, 19], [13, 21], [17, 17]])]),
  c("attending", "Here", "The one who turned up",
    ["here", "in", "turned-up"], ["present-in-class"], ["here", "present", "in class", "turned up"],
    "person", [...PERSON(9, 7, 3), poly([[15, 16], [17, 18], [21, 14]])]),
  c("absent", "Absent", "The one who did not",
    ["absent", "away", "missing"], ["away"], ["absent", "away", "not in", "missing"],
    "person", [...PERSON(9, 7, 3), poly([[16, 14], [22, 20]]), poly([[22, 14], [16, 20]])]),
  c("parent-meeting", "Parents' evening", "Two chairs across a table",
    ["parents", "meeting", "evening"], [], ["parents' evening", "parent meeting", "consultation", "across the table"],
    "figure", [row(12, 2, 22), disc(5, 6, 3), disc(19, 6, 3), poly([[3, 20], [3, 15], [7, 15], [7, 20]]), poly([[17, 20], [17, 15], [21, 15], [21, 20]])]),

  /* ── what is in the case ────────────────────────────────────────────────────── */
  c("school-pencil", "Pencil", "The pencil sharpened to a point",
    ["pencil", "write", "sharp"], [], ["pencil", "a pencil", "write", "sharpened"],
    "pencil", PENCIL()),
  c("pen", "Pen", "The nib on the end of the barrel",
    ["pen", "nib", "ink"], [], ["pen", "fountain pen", "nib", "ink"],
    "pen", [poly([[8, 16], [17, 7], [20, 10], [11, 19]], true), poly([[8, 16], [5, 19], [11, 19]]), poly([[8, 16], [8, 19]])]),
  c("marker-pen", "Marker", "The barrel with a chisel tip",
    ["marker", "chisel", "felt-tip"], ["felt-tip"], ["marker", "marker pen", "felt tip", "chisel tip"],
    "pen", [poly([[8, 14], [16, 6], [20, 10], [12, 18]], true), poly([[5, 17], [8, 14], [12, 18], [9, 21]], true), poly([[10, 16], [14, 12]])]),
  c("chalk", "Chalk", "The stick of chalk",
    ["chalk", "stick", "board"], [], ["chalk", "a stick of chalk", "write on the board", "blackboard"],
    "chalk", [poly([[5, 17], [15, 7], [19, 11], [9, 21]], true), poly([[7, 15], [11, 19]])]),
  c("eraser", "Eraser", "The rubber with its sleeve",
    ["eraser", "rubber", "rub-out"], ["rubber"], ["eraser", "rubber", "rub it out", "correct"],
    "block", [poly([[3, 15], [9, 9], [21, 9], [15, 15]], true), poly([[3, 15], [3, 19], [15, 19], [21, 13], [21, 9]]), poly([[9, 9], [9, 13], [3, 19]])]),
  c("school-ruler", "Ruler", "The edge with its marks",
    ["ruler", "measure", "edge"], [], ["ruler", "measure", "straight edge", "centimetres"],
    "ruler", [poly([[2, 16], [16, 2], [22, 8], [8, 22]], true), poly([[5, 13], [8, 16]]), poly([[9, 9], [12, 12]]), poly([[13, 5], [16, 8]])]),
  c("protractor", "Protractor", "The half circle with its degrees",
    ["protractor", "angle", "degrees"], [], ["protractor", "measure an angle", "degrees", "half circle"],
    "protractor", [arc(12, 17, 9, 180, 360), row(17, 3, 21), arc(12, 17, 5, 180, 360), poly([[12, 8], [12, 11]])]),
  c("drawing-compass", "Compasses", "The two legs and the point between them",
    ["compasses", "circle", "draw"], ["pair-of-compasses"], ["compasses", "draw a circle", "geometry set", "dividers"],
    "compass", [col(12, 3, 9), poly([[12, 9], [6, 15], [6, 19]]), poly([[12, 9], [18, 15], [18, 19]]), poly([[9, 12], [15, 12]])]),
  c("calculator", "Calculator", "The keys under the display",
    ["calculator", "keys", "sums"], [], ["calculator", "work it out", "sums", "keys"],
    "device", [rect(4, 2, 16, 20, 2), row(8, 7, 17), row(12, 7, 17), row(16, 7, 17), col(12, 12, 20)]),
  c("school-notebook", "Notebook", "The pad with its spiral",
    ["notebook", "pad", "spiral"], ["exercise-book"], ["notebook", "exercise book", "pad", "spiral bound"],
    "notebook", [rect(6, 3, 14, 18, 2), col(10, 3, 21), row(9, 13, 17), row(13, 13, 17), row(17, 13, 17)]),
  c("textbook", "Textbook", "The thick book with its spine",
    ["textbook", "book", "spine"], [], ["textbook", "school book", "the book", "set text"],
    "book", [rect(4, 3, 16, 18, 2), col(8, 3, 21), row(8, 11, 17), row(12, 11, 17)]),
  c("school-bag", "School bag", "The rucksack with its straps",
    ["bag", "rucksack", "carry"], [], ["school bag", "rucksack", "backpack", "carry it"],
    "bag", [raw("M4 21V11A8 8 0 0 1 20 11V21Z", "the body of the bag", true), row(15, 4, 20), poly([[9, 4], [9, 7]]), poly([[15, 4], [15, 7]])]),
  c("lunchbox", "Lunchbox", "The box with its handle",
    ["lunchbox", "lunch", "box"], [], ["lunchbox", "packed lunch", "lunch box", "food from home"],
    "case", [rect(3, 8, 18, 12, 2), poly([[9, 8], [9, 5], [15, 5], [15, 8]]), row(13, 3, 21)]),

  /* ── the day ────────────────────────────────────────────────────────────────── */
  c("school-bus", "School bus", "The bus that comes at eight",
    ["bus", "ride", "stop"], [], ["school bus", "the bus", "bus to school", "pick up"],
    "bus", [rect(2, 4, 20, 13, 2), row(9, 2, 22), col(12, 4, 9), disc(7, 19, 2), disc(17, 19, 2)]),
  c("school-bell", "Bell", "The bell that ends the lesson",
    ["bell", "ring", "end"], [], ["school bell", "the bell", "end of lesson", "rings"],
    "bell", [raw("M6 17A6 6 0 0 1 18 17Z", "the bell's skirt", true), poly([[12, 11], [12, 8]]), arc(12, 8, 2, 180, 360), disc(12, 20, 1)]),
  c("school-timetable", "Timetable", "The week with the lessons blocked out",
    ["timetable", "week", "periods"], ["schedule-grid"], ["timetable", "the week", "periods", "what is on when"],
    "grid", [rect(2, 4, 20, 16, 2), poly([[5, 8], [11, 8], [11, 12], [5, 12]], true), poly([[13, 13], [19, 13], [19, 17], [13, 17]], true)]),
  c("lesson", "Lesson", "The board with the hour on it",
    ["lesson", "period", "class"], [], ["lesson", "a lesson", "period", "class time"],
    "board", [BOARD(), row(20, 5, 19), disc(12, 11, 4), poly([[12, 8], [12, 11], [15, 11]])]),
  c("homework", "Homework", "The sheet with a pencil on it",
    ["homework", "sheet", "work"], ["prep"], ["homework", "prep", "work at home", "the sheet"],
    "page", [PAGE(), poly([[8, 17], [16, 9], [18, 11], [10, 19]], true)]),
  c("homework-done", "Homework done", "The sheet handed in",
    ["done", "handed-in", "finished"], [], ["homework done", "handed in", "finished", "complete"],
    "page", [PAGE(), poly([[7, 12], [10, 15], [17, 8]])]),
  c("assignment", "Assignment", "The folder with the task in it",
    ["assignment", "task", "folder"], ["coursework"], ["assignment", "coursework", "the task", "set work"],
    "folder", [poly([[2, 20], [2, 6], [9, 6], [11, 8], [22, 8], [22, 20]], true), row(13, 6, 18), row(16, 6, 14)]),
  c("assignment-due", "Due in", "The task with the hour running",
    ["due", "deadline", "soon"], [], ["due in", "deadline", "hand it in", "due soon"],
    "folder", [poly([[2, 20], [2, 6], [9, 6], [11, 8], [22, 8], [22, 20]], true), disc(15, 14, 4), poly([[15, 11], [15, 14], [18, 14]])]),
  c("grade", "Grade", "The mark on the work",
    ["grade", "mark", "score"], ["mark"], ["grade", "the mark", "marked", "score"],
    "page", [PAGE(), disc(12, 11, 5), poly([[9, 17], [15, 17]])]),
  c("grade-a", "Top grade", "The star on the work",
    ["top", "star", "best"], ["top-grade"], ["top grade", "grade A", "full marks", "a star"],
    "page", [PAGE(), poly([[12, 5], [18, 11], [12, 17], [6, 11]], true)]),
  c("report-card", "Report", "The card with the grade on it",
    ["report", "card", "home"], ["school-report"], ["report", "school report", "goes home", "end of term"],
    "card", [rect(2, 4, 20, 16, 2), row(9, 2, 22), disc(7, 15, 3), row(13, 13, 19), row(17, 13, 19)]),
  c("presentation", "Presentation", "The chart on the stand",
    ["presentation", "stand", "chart"], [], ["presentation", "give a talk", "present", "the stand"],
    "board", [rect(3, 3, 18, 13, 2), poly([[12, 16], [12, 21]]), poly([[7, 21], [12, 16], [17, 21]]), poly([[7, 12], [10, 9], [13, 12], [17, 8]])]),
  c("sports-day", "Sports day", "The podium and the ribbon",
    ["sports", "podium", "race"], ["field-day"], ["sports day", "field day", "races", "podium"],
    "podium", [poly([[8, 21], [8, 8], [16, 8], [16, 21]], true), poly([[2, 21], [2, 13], [8, 13]]), poly([[16, 13], [22, 13], [22, 21]]), disc(12, 4, 2)]),
  c("school-trip", "School trip", "The coach and where it is going",
    ["trip", "coach", "outing"], ["outing"], ["school trip", "outing", "day out", "the coach"],
    "bus", [rect(2, 6, 14, 11, 2), row(10, 2, 16), disc(5, 19, 2), disc(13, 19, 2), poly([[20, 20], [20, 10]]), poly([[20, 6], [16, 10], [20, 10]], true)]),
  c("term", "Term", "The weeks the term runs for",
    ["term", "span", "weeks"], ["semester-span"], ["term", "the term", "weeks of school", "span"],
    "window", [...CAL(), row(15, 6, 18)]),
  c("school-holiday", "Holiday", "The weeks with the sun over them",
    ["holiday", "break", "off"], ["school-break"], ["school holiday", "the holidays", "half term", "break"],
    "window", [...CAL(), arc(12, 17, 4, 180, 360), row(17, 7, 17)]),
  c("graduation", "Graduation", "The cap thrown at the end",
    ["graduation", "cap", "finish"], ["mortarboard"], ["graduation", "mortarboard", "graduate", "the end of it"],
    "cap", [poly([[2, 10], [6, 6], [18, 6], [22, 10], [18, 14], [6, 14]], true), poly([[8, 14], [8, 17], [11, 20], [14, 20], [17, 17], [17, 14]]), poly([[22, 10], [22, 16]])]),
];
