/**
 * R40 · Weather: climate & environment — the warming world and what is done about it.
 *
 * The leaf from R39 stands for what is green, the turbine and the panel for what makes
 * power without smoke, the recycling triangle for what goes round again. The rest are
 * things: a bin, a bottle, a tap, a bird, a bee, a butterfly, a fish.
 */
import { arc, col, disc, poly, raw, rect, row } from "../forms.ts";
import type { Icon } from "../build.ts";

const c = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({
  slug, category: "weather", subcategory: "climate", name, description,
  tags, aliases, keywords, family, shapes,
});

/** A leaf: a curved blade, wide at the foot and drawn to a point, on the diagonal. */
const LEAF = (x: number, y: number, r: number) =>
  raw(`M${x - r} ${y + r}C${x - r} ${y - r * 0.2} ${x - r * 0.2} ${y - r} ${x + r} ${y - r}C${x + r} ${y + r * 0.2} ${x + r * 0.2} ${y + r} ${x - r} ${y + r}Z`,
    "a leaf: two curves from the stem to the tip, wide at the foot", true);
/** The recycling loop: three arrows chasing each other round a triangle. */
const LOOP = () => [
  poly([[6, 14], [11, 9], [15, 9]]), poly([[12.5, 6.5], [15, 9], [12.5, 11.5]]),
  poly([[18, 14], [13, 19], [9, 19]]), poly([[11.5, 16.5], [9, 19], [11.5, 21.5]]),
  poly([[7, 18], [3, 14], [7, 10]]),
];
/** The turbine: a mast with three blades on its hub. */
const TURBINE = () => [col(12, 9, 21), row(21, 8, 16), disc(12, 8, 1), col(12, 2, 7), poly([[13, 9], [18, 14]]), poly([[11, 9], [6, 14]])];
/** A drop, the point above one round belly. */
const DROP = (x: number, y: number, r: number) => raw(`M${x} ${y - r * 2}L${x + r} ${y - r}A${r} ${r} 0 0 1 ${x - r} ${y - r}Z`, "a drop: a point above one round belly", true);
/** The smoke curl a chimney sends up. */
const SMOKE = (x: number, y: number) => [arc(x, y, 2.5, 90, 270), arc(x, y - 5, 2.5, 270, 90)];

export const BATCH_127: Icon[] = [
  /* ── the climate ────────────────────────────────────────────────────────────── */
  c("climate", "Climate", "The thermometer beside the leaf",
    ["climate", "world", "green"], [], ["climate", "world climate", "environment", "planet"],
    "figure", [col(7, 4, 14), disc(7, 17, 3), raw("M20 8C20 14 17 17 12 17C12 11 15 8 20 8Z", "a leaf beside it", true)]),
  c("climate-change", "Climate change", "The globe with a rising line across it",
    ["change", "warming", "trend"], ["global-warming"], ["climate change", "global warming", "warming world", "climate crisis"],
    "orbit", [disc(12, 12, 9), poly([[5, 16], [10, 11], [13, 14], [19, 8]])]),
  c("temperature-anomaly", "Temperature anomaly", "The line running above the average",
    ["anomaly", "average", "above"], [], ["temperature anomaly", "above average", "warming trend", "anomaly"],
    "axes", [col(4, 4, 20), row(20, 4, 20), row(13, 6, 19), poly([[6, 17], [10, 13], [13, 16], [17, 12]])]),
  c("sea-level", "Sea level", "The water rising up the marker",
    ["sea", "level", "rise"], ["sea-level-rise"], ["sea level", "sea level rise", "water rising", "coastal flooding"],
    "figure", [col(6, 3, 21), row(3, 4, 8), row(9, 4, 8), poly([[9, 15], [12, 12], [15, 15], [18, 12], [21, 15]]), poly([[9, 20], [12, 17], [15, 20], [18, 17], [21, 20]])]),
  c("carbon-footprint", "Carbon footprint", "The sole and its toes",
    ["carbon", "footprint", "emissions"], [], ["carbon footprint", "emissions footprint", "carbon", "footprint"],
    "figure", [raw("M7 11A5 5 0 0 1 17 11V17A5 5 0 0 1 7 17Z", "a sole: straight sides into rounded ends", true), disc(7, 5, 1), disc(11, 3.5, 1), disc(15, 3.5, 1), disc(18, 6, 1)]),
  c("carbon-neutral", "Carbon neutral", "The cloud of gas with a check on it",
    ["neutral", "balanced", "offset"], [], ["carbon neutral", "balanced emissions", "offset", "neutral"],
    "cloud", [raw("M5 15A4 4 0 0 1 7 8A5 5 0 0 1 16 7A4.5 4.5 0 0 1 19 15Z", "a cloud: three lobes over a flat foot", true), poly([[8, 18], [11, 21], [16, 16]])]),
  c("net-zero", "Net zero", "The nought with a line through it — nothing left over",
    ["net-zero", "zero", "balance"], [], ["net zero", "zero emissions", "balance to nothing", "climate neutral"],
    "figure", [disc(12, 12, 8), poly([[6, 18], [18, 6]])]),
  c("emissions", "Emissions", "The chimney with its plume",
    ["emissions", "smoke", "output"], [], ["emissions", "smoke stack", "output", "greenhouse gases"],
    "figure", [poly([[6, 21], [6, 11], [12, 11], [12, 21]], true), ...SMOKE(16, 11), row(21, 14, 21)]),
  c("greenhouse-gas", "Greenhouse gas", "The glasshouse with the heat kept in",
    ["greenhouse", "gas", "trapped"], [], ["greenhouse gas", "trapped heat", "greenhouse effect", "ghg"],
    "figure", [poly([[4, 20], [4, 12], [12, 4], [20, 12], [20, 20]], true), disc(12, 14, 3)]),
  c("co-two", "CO2", "The cloud with two rings in it — the gas itself",
    ["co2", "carbon-dioxide", "gas"], ["carbon-dioxide"], ["co2", "carbon dioxide", "greenhouse gas", "emissions"],
    "cloud", [raw("M5 18A4 4 0 0 1 7 11A5 5 0 0 1 16 10A4.5 4.5 0 0 1 19 18Z", "a cloud: three lobes over a flat foot", true), disc(9.5, 14, 2), disc(15, 14, 2)]),

  /* ── the power ──────────────────────────────────────────────────────────────── */
  c("renewable-energy", "Renewable energy", "The leaf with a bolt in it",
    ["renewable", "green", "power"], [], ["renewable energy", "green power", "clean energy", "renewables"],
    "leaf", [LEAF(12, 12, 8), poly([[13, 8], [9.5, 11.5], [12.5, 11.5], [9, 15]])]),
  c("solar-panel", "Solar panel", "The panel with its cells, tilted to the sun",
    ["solar", "panel", "photovoltaic"], ["solar"], ["solar panel", "photovoltaic", "solar power", "pv"],
    "figure", [poly([[4, 14], [10, 8], [20, 8], [14, 14]], true), row(11, 7, 17), col(9, 14, 20), row(20, 5, 13)]),
  c("wind-turbine", "Wind turbine", "The mast with three blades",
    ["turbine", "wind", "power"], [], ["wind turbine", "wind power", "windmill", "wind farm"],
    "figure", TURBINE()),
  c("hydro-power", "Hydro power", "The drop with the current in it",
    ["hydro", "water", "power"], [], ["hydro power", "hydroelectric", "water power", "dam power"],
    "figure", [DROP(12, 20, 8), poly([[14, 8], [9, 13], [12, 13], [8, 17]])]),
  c("geothermal", "Geothermal", "The heat rising out of the ground",
    ["geothermal", "heat", "ground"], [], ["geothermal", "ground heat", "geothermal power", "earth heat"],
    "figure", [row(14, 2, 22), ...SMOKE(8, 9.5), ...SMOKE(16, 9.5), row(20, 6, 18)]),
  c("nuclear-plant", "Nuclear plant", "The cooling tower with its plume",
    ["nuclear", "reactor", "tower"], ["nuclear"], ["nuclear plant", "reactor", "cooling tower", "atomic power"],
    "figure", [poly([[7, 20], [9, 18], [9, 9], [15, 9], [15, 18], [17, 20]], true), ...SMOKE(12, 9.5)]),
  c("coal-plant", "Coal plant", "The two stacks with their smoke",
    ["coal", "fossil", "plant"], ["fossil-fuel"], ["coal plant", "fossil fuel", "coal power", "power station"],
    "figure", [poly([[5, 20], [5, 12], [10, 12], [10, 20]], true), poly([[13, 20], [13, 15], [18, 15], [18, 20]], true), ...SMOKE(7.5, 9.5)]),
  c("gas-flame", "Gas", "The flame of a burner",
    ["gas", "flame", "burn"], [], ["gas", "gas flame", "burner", "natural gas"],
    "figure", [raw("M12 3C14 7 18 9 18 14A6 6 0 1 1 6 14C6 10 9 9 9 6C10 7 12 7 12 3Z", "a flame: the tongue curling up from a round belly", true), row(21, 5, 19)]),
  c("energy-saving", "Energy saving", "The bulb with a leaf in it",
    ["saving", "efficient", "less"], ["efficiency"], ["energy saving", "efficient", "use less power", "energy efficiency"],
    "figure", [arc(12, 10, 6, 180, 360), poly([[8, 10], [8, 16], [16, 16], [16, 10]]), row(19, 9, 15), LEAF(12, 10, 3)]),
  c("insulation", "Insulation", "The wall with its layers keeping the heat in",
    ["insulation", "layers", "warm"], [], ["insulation", "loft insulation", "keep the heat", "thermal layer"],
    "figure", [poly([[4, 4], [4, 20], [10, 20], [10, 4]], true), poly([[12, 4], [12, 20]]), poly([[15, 4], [15, 20]]), poly([[18, 4], [18, 20]])]),

  /* ── what goes round ────────────────────────────────────────────────────────── */
  c("recycle", "Recycle", "Three arrows chasing each other round",
    ["recycle", "loop", "reuse"], ["recycling"], ["recycle", "recycling", "reuse", "circular"],
    "loop", LOOP()),
  c("recycle-bin", "Recycling bin", "The bin with the loop on it",
    ["bin", "recycle", "waste"], [], ["recycling bin", "recycle bin", "waste bin", "sort your waste"],
    "figure", [poly([[6, 8], [6, 21], [18, 21], [18, 8]]), row(8, 3, 21), poly([[9, 8], [9, 5], [15, 5], [15, 8]]), poly([[9, 17], [12, 14], [15, 17]])]),
  c("compost", "Compost", "The heap with a sprout coming out of it",
    ["compost", "heap", "organic"], [], ["compost", "compost heap", "food waste", "organic waste"],
    "figure", [arc(12, 20, 9, 180, 360), row(20, 3, 21), col(12, 9, 15), LEAF(9, 9, 3), LEAF(15, 9, 3)]),
  c("landfill", "Landfill", "The mound of waste with the ground under it",
    ["landfill", "waste", "dump"], ["dump"], ["landfill", "waste dump", "rubbish tip", "buried waste"],
    "figure", [poly([[3, 15], [8, 10], [13, 15], [18, 10], [21, 13]]), row(18, 2, 22), poly([[9, 13], [11, 11]])]),
  c("plastic-free", "Plastic free", "The bottle with a line through it",
    ["plastic", "free", "none"], ["no-plastic"], ["plastic free", "no plastic", "avoid plastic", "plastic ban"],
    "figure", [poly([[9, 8], [9, 20], [15, 20], [15, 8]], true), poly([[10.5, 8], [10.5, 4], [13.5, 4], [13.5, 8]]), poly([[5, 20], [19, 6]])]),
  c("reusable-bag", "Reusable bag", "The bag with its handles",
    ["bag", "reusable", "shopping"], ["tote"], ["reusable bag", "tote bag", "bag for life", "shopping bag"],
    "figure", [poly([[6, 8], [6, 21], [18, 21], [18, 8]], true), arc(9, 8, 3, 180, 360), arc(15, 8, 3, 180, 360)]),
  c("reusable-bottle", "Reusable bottle", "The flask with its cap and band",
    ["bottle", "flask", "refill"], ["water-bottle"], ["reusable bottle", "water bottle", "refillable", "flask"],
    "figure", [poly([[8, 7], [8, 21], [16, 21], [16, 7]], true), poly([[10, 7], [10, 3], [14, 3], [14, 7]]), row(12, 8, 16)]),
  c("litter-pick", "Litter pick", "The grabber picking up a piece of litter",
    ["litter", "pick", "clean-up"], ["clean-up"], ["litter pick", "clean up", "pick up litter", "tidy up"],
    "figure", [poly([[4, 4], [13, 13]]), poly([[13, 13], [10, 16]]), poly([[13, 13], [16, 16]]), poly([[8, 19], [14, 19], [14, 22], [8, 22]], true)]),
  c("eco-label", "Eco label", "The label with a leaf on it",
    ["label", "eco", "certified"], [], ["eco label", "eco certified", "green label", "environment mark"],
    "label", [poly([[4, 12], [12, 4], [20, 4], [20, 12], [12, 20]], true), LEAF(14, 10, 3.5)]),
  c("organic", "Organic", "The leaf in a ring",
    ["organic", "natural", "certified"], [], ["organic", "natural", "organic certified", "no chemicals"],
    "leaf", [disc(12, 12, 9), LEAF(12, 12, 5)]),
  c("fair-trade", "Fair trade", "The scales hanging level",
    ["fair", "trade", "exchange"], [], ["fair trade", "fair exchange", "ethical trade", "fairtrade"],
    "scales", [col(12, 4, 20), row(6, 4, 20), arc(6, 6, 3, 0, 180), arc(18, 6, 3, 0, 180), row(20, 8, 16)]),
  c("green-building", "Green building", "The block with a leaf on its roof",
    ["building", "green", "sustainable"], [], ["green building", "sustainable building", "eco house", "leed"],
    "figure", [poly([[5, 21], [5, 10], [19, 10], [19, 21]], true), row(15, 5, 19), LEAF(12, 6, 3.5)]),
  c("bike-share", "Bike share", "The bike waiting at its post",
    ["bike", "share", "hire"], [], ["bike share", "cycle hire", "shared bikes", "bike scheme"],
    "figure", [disc(7, 15, 3.5), disc(17, 15, 3.5), poly([[7, 15], [10, 12], [14, 12], [17, 15]]), col(10, 8, 12), poly([[3, 6], [3, 19]])]),

  /* ── the water ──────────────────────────────────────────────────────────────── */
  c("water-saving", "Water saving", "The drop with a line through it",
    ["water", "saving", "less"], [], ["water saving", "save water", "use less water", "water efficiency"],
    "figure", [DROP(12, 16, 6), poly([[5, 19], [19, 5]])]),
  c("rainwater", "Rainwater", "Drops falling into the butt",
    ["rainwater", "harvest", "butt"], ["rainwater-harvest"], ["rainwater", "rain harvesting", "water butt", "collect rain"],
    "figure", [poly([[7, 13], [7, 20], [17, 20], [17, 13]]), row(13, 5, 19), DROP(9, 9, 2), DROP(15, 8, 2)]),
  c("tap-water", "Tap water", "The tap with a drop under it",
    ["tap", "water", "mains"], ["faucet"], ["tap water", "faucet", "mains water", "running water"],
    "figure", [poly([[4, 6], [12, 6], [12, 12], [16, 12]]), col(9, 3, 6), row(3, 6, 12), DROP(16, 19, 3)]),
  c("drinking-water", "Drinking water", "The glass with the drop in it",
    ["drinking", "water", "glass"], [], ["drinking water", "potable water", "safe to drink", "glass of water"],
    "figure", [poly([[7, 5], [7, 21], [17, 21], [17, 5]], true), DROP(12, 15, 3), row(9, 7, 17)]),
  c("water-quality", "Water quality", "The drop with a tick in it",
    ["quality", "clean", "tested"], [], ["water quality", "clean water", "tested water", "safe water"],
    "figure", [DROP(12, 20, 8), poly([[8, 13], [11, 16], [16, 11]])]),

  /* ── the living world ───────────────────────────────────────────────────────── */
  c("tree-planting", "Tree planting", "The sapling going into the ground",
    ["planting", "sapling", "new"], [], ["tree planting", "plant a tree", "sapling", "new tree"],
    "tree", [poly([[12, 17], [12, 9]]), raw("M12 9C12 5 9 3 5 3C5 7 8 9 12 9Z", "a first leaf", true), raw("M12 12C12 8 15 6 19 6C19 10 16 12 12 12Z", "a second leaf", true), arc(12, 21, 7, 180, 360)]),
  c("reforestation", "Reforestation", "Trees going back in, one after another",
    ["reforestation", "replant", "forest"], ["replant"], ["reforestation", "replanting", "forest restored", "plant trees"],
    "tree", [disc(7, 9, 4), col(7, 13, 19), disc(17, 12, 4), col(17, 16, 19), row(19, 2, 22)]),
  c("deforestation", "Deforestation", "The stump and the tree that came off it",
    ["deforestation", "felled", "stump"], ["logging"], ["deforestation", "logging", "trees felled", "clearing"],
    "figure", [poly([[5, 19], [5, 14], [11, 14], [11, 19]]), poly([[12, 18], [18, 12]]), disc(18, 8, 3)]),
  c("biodiversity", "Biodiversity", "A leaf and a paw, side by side",
    ["biodiversity", "variety", "species"], [], ["biodiversity", "variety of life", "species", "ecosystem"],
    "figure", [raw("M10 5C10 11 7 14 2 14C2 8 5 5 10 5Z", "a leaf for the plants", true), disc(14, 9, 2), disc(19, 10, 2), raw("M13 16A5 5 0 0 1 22 16A4 4 0 0 1 17.5 20A4 4 0 0 1 13 16Z", "a paw for the animals", true)]),
  c("endangered", "Endangered", "The paw with a warning beside it",
    ["endangered", "risk", "species"], [], ["endangered", "at risk species", "threatened", "red list"],
    "figure", [disc(6, 8, 2), disc(11, 6, 2), raw("M3 16A5 5 0 0 1 13 16A4 4 0 0 1 8 20A4 4 0 0 1 3 16Z", "the pad under the toes", true), col(19, 6, 14), disc(19, 17, 1)]),
  c("wildlife", "Wildlife", "A paw print in the ground",
    ["wildlife", "animals", "paw"], ["animals"], ["wildlife", "animals", "paw print", "wild animals"],
    "figure", [disc(6, 9, 2), disc(11, 6, 2), disc(16, 8, 2), raw("M6 17A5.5 5.5 0 0 1 17 17A4.5 4.5 0 0 1 11.5 21A4.5 4.5 0 0 1 6 17Z", "the pad: one arc over the toes and a rounded heel", true)]),
  c("bird", "Bird", "The bird on a branch",
    ["bird", "flight", "wings"], [], ["bird", "in flight", "wings", "flying bird"],
    "figure", [disc(15, 8, 3), raw("M6 18C6 13 10 10 14 11C17 12 18 15 16 18Z", "the body, tapering to the tail", true), poly([[18, 6], [21, 9], [18, 9]], true), poly([[6, 18], [3, 21]])]),
  c("bee", "Bee", "The striped body with a wing either side",
    ["bee", "pollinator", "insect"], [], ["bee", "honeybee", "pollinator", "insect"],
    "figure", [raw("M8 9A4 4 0 0 1 16 9V17A4 4 0 0 1 8 17Z", "the body: straight sides into rounded ends", true), row(12, 8.5, 15.5), row(16, 9, 15), raw("M8 10C5 6 2 9 3 12C4 15 7 14 8 10Z", "the wing on the left", true), raw("M16 10C19 6 22 9 21 12C20 15 17 14 16 10Z", "the wing on the right", true)]),
  c("butterfly", "Butterfly", "Two wings either side of the body",
    ["butterfly", "wings", "insect"], [], ["butterfly", "wings", "insect", "moth"],
    "figure", [col(12, 6, 19), raw("M12 8C9 4 3 5 3 9C3 12 6 13 8 12C5 14 4 17 6 19C8 21 12 18 12 15", "the wings on the left", false), raw("M12 8C15 4 21 5 21 9C21 12 18 13 16 12C19 14 20 17 18 19C16 21 12 18 12 15", "the wings on the right", false)]),
  c("wild-fish", "Fish", "The body with its tail",
    ["fish", "sea", "wild"], [], ["fish", "wild fish", "sea life", "fishing"],
    "figure", [raw("M4 13A8 5 0 0 1 18 13A8 5 0 0 1 4 13Z", "the body: two arcs meeting at nose and tail", true), poly([[17, 9], [21, 13], [17, 17]]), disc(8, 11, 1)]),
  c("coral-bleach", "Coral bleaching", "The coral with a cross over it",
    ["coral", "bleaching", "dying"], [], ["coral bleaching", "dying reef", "bleached coral", "reef damage"],
    "figure", [poly([[8, 21], [8, 12], [5, 9]]), poly([[8, 15], [12, 11]]), poly([[15, 21], [15, 11], [12, 8]]), row(21, 3, 21), poly([[16, 4], [21, 9]]), poly([[21, 4], [16, 9]])]),
  c("ocean-plastic", "Ocean plastic", "The bottle floating in the waves",
    ["plastic", "ocean", "pollution"], [], ["ocean plastic", "plastic in the sea", "marine litter", "sea pollution"],
    "figure", [poly([[9, 5], [9, 14], [15, 14], [15, 5]], true), poly([[10.5, 5], [10.5, 2], [13.5, 2], [13.5, 5]]), poly([[3, 18], [6, 15], [9, 18], [12, 15], [15, 18], [18, 15], [21, 18]])]),
];
