/**
 * R04 · API design & integration — the vocabulary of building and consuming HTTP APIs.
 *
 * The grammar is the campaign's: every icon is one body holding its content. The verbs
 * live between brackets the way the block family does; documents are page(); consoles
 * and screens are panel(); everything that repeats rides cycle(); the sunset is drawn
 * as a sun, because that is what the header means.
 */
import { arc, col, disc, poly, rect, row } from "../forms.ts";
import { brackets, cycle, dial, eventCard, machine, padlock, page, panel, runCard, tray } from "../bodies.ts";
import { BIG, SMALL, add, alert, boltMark, check, clockMark, diamondMark, funnelMark, keyMark, off, pinMark, playMark, remove, tagMark, trendMark } from "../marks.ts";
import type { Icon } from "../build.ts";

const api = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({
  slug, category: "devtools", subcategory: "api", name, description,
  tags, family, aliases, keywords, shapes,
});

export const BATCH_91: Icon[] = [
  /* ── the verbs, held between brackets ─────────────────────────────────────────── */
  api("http-get", "HTTP GET", "An arrow coming down between brackets — a GET request, fetching a resource to read",
    ["get", "fetch", "read"], [], ["http get", "fetch resource", "read request", "rest get"],
    "bracket", [...brackets(), col(12, 8.5, 14), poly([[9.5, 11.5], [12, 14], [14.5, 11.5]])]),
  api("http-post", "HTTP POST", "An arrow rising between brackets — a POST request, sending something new to the server",
    ["post", "create", "send"], [], ["http post", "create resource", "submit", "rest post"],
    "bracket", [...brackets(), col(12, 10, 15.5), poly([[9.5, 12.5], [12, 10], [14.5, 12.5]])]),
  api("http-put", "HTTP PUT", "An arrow rising to a bar between brackets — a PUT request, replacing the whole resource",
    ["put", "replace", "update"], [], ["http put", "replace resource", "full update", "rest put"],
    "bracket", [...brackets(), row(7.5, 9.5, 14.5), col(12, 10.5, 16), poly([[9.5, 13], [12, 10.5], [14.5, 13]])]),
  api("http-patch", "HTTP PATCH", "A plus over a minus between brackets — a PATCH request, changing only what it names",
    ["patch", "partial", "update"], [], ["http patch", "partial update", "modify field", "rest patch"],
    "bracket", [...brackets(), col(12, 7.5, 11.5), row(9.5, 10, 14), row(14.5, 10, 14)]),
  api("http-delete", "HTTP DELETE", "A minus between brackets — a DELETE request, taking the resource away for good",
    ["delete", "remove", "destroy"], [], ["http delete", "remove resource", "destroy", "rest delete"],
    "bracket", [...brackets(), ...remove(SMALL, 12)]),

  /* ── parameters and shapes of a request ───────────────────────────────────────── */
  api("query-param", "Query param", "A question mark between brackets — the query string, questions appended to the URL",
    ["query", "parameter", "url"], [], ["query string", "url parameter", "search param", "?key=value"],
    "bracket", [...brackets(), arc(12, 10.5, 2.5, 180, 90), disc(12, 15.5, 1)]),
  api("path-param", "Path param", "A placeholder dot between brackets — a segment of the path filled in at request time",
    ["path", "parameter", "segment"], [], ["path parameter", "route param", "url segment", "placeholder"],
    "bracket", [...brackets(), disc(12, 12, 2)]),
  api("field-mask", "Field mask", "A funnel between brackets — ask for only the fields you need and no others",
    ["fields", "mask", "select"], [], ["field mask", "sparse fields", "partial fields", "projection"],
    "bracket", [...brackets(), ...funnelMark(SMALL, 12)]),
  api("batch-request", "Batch request", "Three rows between brackets — many calls travelling together as a single request",
    ["batch", "bundle", "many"], [], ["batch request", "bundled calls", "multi request", "batching"],
    "bracket", [...brackets(), row(8.5, 9, 15), row(12, 9, 15), row(15.5, 9, 15)]),
  api("idempotent-post", "Idempotent POST", "An equals sign between brackets — send it twice and the result stays the same",
    ["idempotent", "safe", "retry"], [], ["idempotency key", "safe retry", "exactly once", "duplicate safe"],
    "bracket", [...brackets(), row(10, 9, 15), row(14, 9, 15)]),
  api("request-id-api", "Request ID", "A pin between brackets — the id that marks one request through every log it touches",
    ["request-id", "trace", "correlate"], [], ["request id", "correlation id", "trace request", "x-request-id"],
    "bracket", [...brackets(), ...pinMark(SMALL, 12)]),
  api("api-mock", "API mock", "An empty square between brackets — a stand-in that answers while the real API is unbuilt",
    ["mock", "stub", "fake"], [], ["mock api", "stub server", "fake response", "test double"],
    "bracket", [...brackets(), poly([[9, 9], [15, 9], [15, 15], [9, 15]], true)]),

  /* ── documents: contracts, schemas, payloads ──────────────────────────────────── */
  api("api-version", "API version", "A document with a pin below its title — the version a client pins and builds against",
    ["version", "semver", "pin"], [], ["api version", "versioning", "v1 v2", "version pin"],
    "page", [page(), row(7, 9, 15), ...pinMark(SMALL, 14)]),
  api("api-deprecate", "API deprecate", "A document with an X below its title — an endpoint marked for removal, use it no more",
    ["deprecated", "retire", "legacy"], [], ["deprecated api", "retire endpoint", "legacy api", "removal notice"],
    "page", [page(), row(7, 9, 15), ...off(SMALL, 14)]),
  api("api-contract", "API contract", "A document with a check below its title — the agreed shape both sides build against",
    ["contract", "agreement", "spec"], [], ["api contract", "openapi spec", "contract testing", "agreed schema"],
    "page", [page(), row(7, 9, 15), ...check(SMALL, 14)]),
  api("graphql-schema", "GraphQL schema", "A type node above its field rows — the schema a graph query is written against",
    ["graphql", "schema", "types"], [], ["graphql schema", "type system", "sdl", "graph types"],
    "page", [page(), ...diamondMark(SMALL, 9), row(15, 9, 15), row(18, 9, 15)]),
  api("api-diff", "API diff", "A document with a plus above and a minus below — what changed between two versions",
    ["diff", "changes", "compare"], [], ["api diff", "breaking change", "changelog", "schema diff"],
    "page", [page(), col(9, 7, 11), row(9, 7, 11), row(15, 13, 17)]),
  api("request-body", "Request body", "An arrow arriving above a row — the payload a request carries in with it",
    ["body", "payload", "input"], [], ["request body", "payload", "post body", "input document"],
    "page", [page(), col(12, 6.5, 10.5), poly([[9.5, 8.5], [12, 11], [14.5, 8.5]]), row(15.5, 9, 15)]),
  api("response-body", "Response body", "An arrow leaving above a row — the payload an answer brings back out",
    ["response", "payload", "output"], [], ["response body", "response payload", "output document", "result body"],
    "page", [page(), col(12, 6, 10.5), poly([[9.5, 8.5], [12, 6], [14.5, 8.5]]), row(15.5, 9, 15)]),
  api("header-request", "Request headers", "Two rows at the top and nothing after — the header block that rides ahead of the body",
    ["headers", "metadata", "http"], [], ["request headers", "http header", "metadata block", "header fields"],
    "page", [page(), row(6.5, 9, 15), row(9.5, 9, 12)]),
  api("partial-response", "Partial response", "Rows that trail off — a response cut short on purpose, the rest left unfetched",
    ["partial", "truncated", "less"], [], ["partial response", "truncated body", "partial content", "206"],
    "page", [page(), row(7, 9, 15), row(10.5, 9, 15), row(14, 9, 11.5)]),
  api("etag", "ETag", "A label below the title row — the tag a cache compares before fetching again",
    ["etag", "cache", "validator"], [], ["etag header", "cache validator", "if-none-match", "304"],
    "page", [page(), row(7, 9, 15), ...tagMark(SMALL, 14)]),
  api("conditional-request", "Conditional request", "A question below the title row — a request that only proceeds if its condition holds",
    ["conditional", "if", "guard"], [], ["conditional request", "if-match", "precondition", "412"],
    "page", [page(), row(6.5, 9, 15), arc(12, 12, 2.5, 180, 90), disc(12, 17, 1)]),
  api("media-type", "Media type", "A play below the title row — the document that says what kind of content follows",
    ["media", "content-type", "mime"], [], ["media type", "content type", "mime type", "accept header"],
    "page", [page(), row(7, 9, 15), ...playMark(SMALL, 14)]),
  api("event-payload", "Event payload", "A bolt below the title row — the document an event carries to whoever listens",
    ["event", "payload", "webhook"], [], ["event payload", "webhook body", "event data", "message body"],
    "page", [page(), row(7, 9, 15), ...boltMark(SMALL, 14)]),
  api("rate-headers", "Rate limit headers", "Quota bars under the title row — how much budget the response says is left",
    ["rate", "quota", "headers"], [], ["rate limit headers", "x-ratelimit", "quota remaining", "429"],
    "page", [page(), row(7, 9, 15), col(9, 11.5, 16), col(12, 9.5, 16), col(15, 13, 16)]),
  api("request-signing", "Request signing", "A key below the title row — a request signed so the server knows who sent it",
    ["signing", "signature", "auth"], [], ["request signing", "signed request", "sigv4", "signature"],
    "page", [page(), row(7, 9, 15), ...keyMark(SMALL, 14)]),
  api("pagination-cursor", "Cursor pagination", "Rows and a chevron pointing on — continue from exactly where the last page ended",
    ["cursor", "pagination", "next"], [], ["cursor pagination", "next page token", "continuation", "seek method"],
    "page", [page(), row(7, 9, 15), row(10.5, 9, 15), poly([[10, 14.5], [12, 16.5], [14, 14.5]])]),
  api("pagination-offset", "Offset pagination", "Rows above a row of page dots — pick a numbered page and read from there",
    ["offset", "pagination", "skip"], [], ["offset pagination", "limit offset", "page number", "skip rows"],
    "page", [page(), row(7, 9, 15), row(10.5, 9, 15), disc(8, 17, 1), disc(12, 17, 1), disc(16, 17, 1)]),
  api("content-negotiation", "Content negotiation", "Arrows trading places on a document — client and server agreeing on a format",
    ["negotiation", "accept", "format"], [], ["content negotiation", "accept header", "format agreement", "vary"],
    "page", [page(), row(9, 8, 13), poly([[12.5, 6.5], [15, 9], [12.5, 11.5]]), row(15, 11, 16), poly([[11.5, 12.5], [9, 15], [11.5, 17.5]])]),

  /* ── screens: consoles, playgrounds, analytics ────────────────────────────────── */
  api("api-playground", "API playground", "A screen with a play inside — try a request against the live API and see what returns",
    ["playground", "try", "explore"], [], ["api playground", "try it", "api explorer", "interactive docs"],
    "window", [panel(), ...playMark(SMALL, 12)]),
  api("api-console", "API console", "A prompt and a cursor line on a screen — the console where requests are typed by hand",
    ["console", "prompt", "shell"], [], ["api console", "rest console", "query console", "http shell"],
    "window", [panel(), poly([[7, 9.5], [9.5, 12], [7, 14.5]]), row(14.5, 12, 16.5)]),
  api("api-usage", "API usage", "A line rising on a screen — how many calls an API serves as the days go by",
    ["usage", "calls", "traffic"], [], ["api usage", "call volume", "requests per day", "traffic graph"],
    "window", [panel(), ...trendMark(SMALL, 11)]),
  api("api-analytics", "API analytics", "Bars standing on a screen — which endpoints are hit, by whom, and how hard",
    ["analytics", "metrics", "endpoints"], [], ["api analytics", "endpoint metrics", "api dashboard", "usage breakdown"],
    "window", [panel(), col(9, 10, 15), col(12, 8, 15), col(15, 11, 15)]),
  api("client-credentials", "Client credentials", "A key on a screen — a credential a program presents for itself, no person involved",
    ["oauth", "machine", "service"], [], ["client credentials", "machine to machine", "service account", "oauth m2m"],
    "window", [panel(), ...keyMark(SMALL, 12)]),
  api("device-code", "Device code", "A short code of dots on a screen — the code you read off one device and type into another",
    ["device", "code", "oauth"], [], ["device code flow", "activation code", "tv login", "enter code"],
    "window", [panel(), disc(8, 12, 1), disc(12, 12, 1), disc(16, 12, 1)]),

  /* ── things that repeat ride the cycle ────────────────────────────────────────── */
  api("refresh-token-api", "Refresh token", "A token pill inside the loop — trade it in and the session quietly starts over",
    ["refresh", "token", "renew"], [], ["refresh token", "token renewal", "silent refresh", "session extend"],
    "rotation", [...cycle(), rect(9, 10.5, 6, 3, 1.5)]),
  api("api-key-rotate", "API key rotate", "A key inside the loop — retire the old credential and issue its replacement",
    ["rotate", "key", "credential"], [], ["key rotation", "rotate credentials", "new api key", "rollover"],
    "rotation", [...cycle(), ...keyMark(SMALL, 12)]),
  api("webhook-retry", "Webhook retry", "A bolt inside the loop — a delivery that failed once and will be tried again",
    ["webhook", "retry", "redeliver"], [], ["webhook retry", "redelivery", "retry backoff", "failed delivery"],
    "rotation", [...cycle(), ...boltMark(SMALL, 12)]),
  api("operation-poll", "Operation polling", "A clock inside the loop — ask again on a timer until the work reports done",
    ["poll", "status", "wait"], [], ["polling", "status check", "poll until done", "check progress"],
    "rotation", [...cycle(), ...clockMark(SMALL, 12)]),

  /* ── cards, locks, and the rest ───────────────────────────────────────────────── */
  api("webhook-secret", "Webhook secret", "An event card with a key under its bolt — the shared secret that proves the sender",
    ["webhook", "secret", "verify"], [], ["webhook secret", "signature verification", "shared secret", "hmac check"],
    "window", [...eventCard(), ...keyMark(SMALL, 16)]),
  api("webhook-delivery", "Webhook delivery", "An event card with a check under its bolt — the event arrived and was acknowledged",
    ["webhook", "delivered", "sent"], [], ["webhook delivery", "delivered event", "200 ok", "acknowledged"],
    "window", [...eventCard(), ...check(SMALL, 16)]),
  api("long-running-operation", "Long-running operation", "A run card with a clock under its play — work that answers later, not now",
    ["async", "operation", "job"], [], ["long running operation", "async job", "operation id", "202 accepted"],
    "window", [...runCard(), ...clockMark(SMALL, 16)]),
  api("hmac-signature", "HMAC signature", "A padlock with a key on its body — a message sealed so tampering shows at once",
    ["hmac", "signature", "integrity"], [], ["hmac signature", "message integrity", "signed payload", "sha256 hmac"],
    "lock", [...padlock(), ...keyMark(SMALL, 15.5)]),
  api("sandbox-api", "Sandbox API", "A play seated in an open box — requests land somewhere real money never moves",
    ["sandbox", "test", "safe"], [], ["sandbox environment", "test mode", "fake data", "safe testing"],
    "tray", [tray(), ...playMark(BIG, 9)]),
  api("bulk-endpoint", "Bulk endpoint", "Stacked rows over an open box — one endpoint built to swallow the whole load",
    ["bulk", "import", "mass"], [], ["bulk endpoint", "bulk import", "mass update", "bulk operations"],
    "tray", [tray(), row(5.5, 8, 16), row(9, 8, 16), row(12.5, 8, 16)]),
  api("sdk-generate", "SDK generate", "Brackets inside the machine — client code produced straight from the API's own spec",
    ["sdk", "codegen", "client"], [], ["sdk generation", "codegen", "generated client", "openapi generator"],
    "machine", [machine(), poly([[10.5, 8.5], [8, 8.5], [8, 15.5], [10.5, 15.5]]), poly([[13.5, 8.5], [16, 8.5], [16, 15.5], [13.5, 15.5]])]),
  api("api-lint", "API lint", "A lens reading two rows closely — the spec checked line by line against the style rules",
    ["lint", "style", "check"], [], ["api linting", "spec lint", "style guide", "spectral"],
    "magnifier", [disc(12, 10, 6.5), poly([[16.5, 14.5], [21, 19]]), row(8, 9.5, 14.5), row(11, 9.5, 14.5)]),
  api("sunset-header", "Sunset header", "A sun going down to the horizon line — the header naming the day an API goes away",
    ["sunset", "shutdown", "date"], [], ["sunset header", "api shutdown", "end of life", "deprecation date"],
    "figure", [arc(12, 15, 5, 180, 360), row(18, 4, 20), col(12, 4.5, 7), poly([[5, 8], [7, 10]]), poly([[19, 8], [17, 10]])]),
  api("retry-after", "Retry after", "A timer dial with a chevron on its face — come back when the clock says you may",
    ["retry", "backoff", "wait"], [], ["retry after", "backoff", "429 retry", "wait period"],
    "orbit", [...dial(), poly([[10.5, 11], [13.5, 14], [10.5, 17]])]),
];
