/**
 * R20 · MCP & agent orchestration depth — what a server offers and enforces, and how a
 * crowd of agents is told who does what.
 *
 * A server is the rack `mcp-server` stands in, with what it does drawn in the rack. An agent
 * is the open ring `agent` is drawn in, with its role or its limit inside. A tool is the
 * two-pronged plug `mcp-tool-call` draws, with the mark on its body. The one loop is the
 * rotation loop.
 */
import { arc, col, disc, poly, rect, row } from "../forms.ts";
import { cycle, ring, server } from "../bodies.ts";
import {
  SMALL, check, clockMark, funnelMark, heartMark, listMark, lockMark, shieldMark, tagMark,
} from "../marks.ts";
import type { Icon } from "../build.ts";

type Sub = "server" | "multi-agent" | "execution" | "tool-use";
const m = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({ slug, category: "mcp", subcategory: "server", name, description, tags, aliases, keywords, family, shapes });
const a = (sub: Sub) => (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({ slug, category: "agents", subcategory: sub, name, description, tags, aliases, keywords, family, shapes });
const orch = a("multi-agent"), run = a("execution"), use = a("tool-use");

/** The two-pronged plug `mcp-tool-call` draws. Marks sit on the body at cy 15.5. */
const PLUG = () => [rect(6, 11, 12, 9, 2), col(9, 4, 11), col(15, 4, 11)];
/** The set's bolt, 2.5 wide, with its top-right corner at (x, y). */
const BOLT = (x: number, y: number) => poly([[x, y], [x - 2.5, y + 2.5], [x, y + 2.5], [x - 2.5, y + 5]]);

export const BATCH_107: Icon[] = [
  /* ── In the rack ──────────────────────────────────────────────────────────────── */
  m("mcp-capability-negotiate", "Capability negotiation", "The rack with an arrow pointing both ways — client and server agreeing on what each can do",
    ["capability", "negotiate", "handshake"], [], ["capability negotiation", "initialize handshake", "supported features", "protocol negotiation"],
    "machine", [...server(), row(11, 8, 16), poly([[10.5, 8.5], [8, 11], [10.5, 13.5]]), poly([[13.5, 8.5], [16, 11], [13.5, 13.5]])]),
  m("mcp-resource-update", "Resource update", "The rack with an arrow looping back — a resource the server says has changed",
    ["resource", "update", "notify"], [], ["resource updated", "resources/updated", "resource changed", "refresh resource"],
    "machine", [...server(), poly([[7.5, 13.5], [7.5, 8.5], [14.5, 8.5], [14.5, 13.5]]), poly([[12, 11], [14.5, 13.5], [17, 11]])]),
  m("mcp-prompt-template", "Prompt template", "The rack with brackets in it — a prompt with the blanks still to fill",
    ["prompt", "template", "arguments"], [], ["prompt template", "templated prompt", "prompt with arguments", "fill in the blanks"],
    "machine", [...server(), poly([[10.5, 8], [8, 8], [8, 14], [10.5, 14]]), poly([[13.5, 8], [16, 8], [16, 14], [13.5, 14]])]),
  m("mcp-tool-annotation", "Tool annotation", "The rack with a tag in it — hints about a tool: read-only, destructive, idempotent",
    ["tool", "annotation", "hint"], [], ["tool annotation", "tool hints", "read-only hint", "destructive hint"],
    "machine", [...server(), ...tagMark(SMALL, 11)]),
  m("mcp-progress-token", "Progress token", "The rack with a bar in it — the token a long request reports its progress against",
    ["progress", "token", "request"], [], ["progress token", "progress notification", "long-running request", "progress bar"],
    "machine", [...server(), rect(7.5, 9, 9, 4, 2)]),
  m("mcp-cancel-request", "Cancel request", "The rack with a slash in it — a request the client no longer wants answered",
    ["cancel", "request", "abort"], [], ["cancel request", "cancelled notification", "abort request", "stop request"],
    "machine", [...server(), poly([[9, 8], [15, 14]])]),
  m("mcp-rate-limit", "Rate limit", "The rack with a funnel in it — only so many calls let through in a window",
    ["rate", "limit", "throttle"], [], ["rate limit", "throttling", "too many requests", "calls per minute"],
    "machine", [...server(), ...funnelMark(SMALL, 11)]),
  m("mcp-auth-flow", "Auth flow", "The rack with a lock in it — the steps a client goes through to be let in",
    ["auth", "flow", "oauth"], [], ["auth flow", "authorization flow", "oauth flow", "login to server"],
    "machine", [...server(), ...lockMark(SMALL, 11)]),
  m("mcp-scope-grant", "Scope grant", "The rack with a funnel and a check under it — the scopes a client asked for and got",
    ["scope", "grant", "auth"], [], ["scope grant", "granted scopes", "scope approval", "consented scopes"],
    "machine", [...server(), poly([[9, 7], [12, 10], [15, 7]]), poly([[9.5, 13], [11.5, 15], [15, 11.5]])]),
  m("mcp-server-health", "Server health", "The rack with a heart in it — whether the server is alive and answering",
    ["health", "status", "monitor"], [], ["server health", "health check", "server alive", "liveness"],
    "machine", [...server(), ...heartMark(SMALL, 11)]),
  m("mcp-server-log", "Server log", "The rack with lines in it — what the server wrote while it ran",
    ["log", "output", "monitor"], [], ["server log", "server output", "log messages", "logging level"],
    "machine", [...server(), ...listMark(SMALL, 11)]),
  m("mcp-server-metric", "Server metric", "The rack with bars in it — how much the server is doing, measured",
    ["metric", "usage", "monitor"], [], ["server metric", "server metrics", "call counts", "latency per tool"],
    "machine", [...server(), col(9, 10, 14), col(12, 8, 14), col(15, 11, 14)]),
  m("mcp-multi-server", "Multi-server", "The rack with two slots in it — several servers behind one client",
    ["multi", "servers", "client"], [], ["multi-server", "many servers", "server list", "connected servers"],
    "machine", [...server(), row(8.5, 9, 15), row(12.5, 9, 15)]),
  m("mcp-proxy", "Proxy", "The rack with a relay point on a wire — a server that passes calls on to another",
    ["proxy", "relay", "forward"], [], ["mcp proxy", "proxy server", "relay server", "pass-through"],
    "machine", [...server(), row(11, 7, 10), disc(12, 11, 2), row(11, 14, 17)]),
  m("mcp-gateway", "Gateway", "The rack with two posts in it — the one door many servers sit behind",
    ["gateway", "entry", "route"], [], ["mcp gateway", "gateway server", "single entry point", "aggregating gateway"],
    "machine", [...server(), col(9, 7, 15), col(15, 7, 15)]),
  m("mcp-discovery", "Server discovery", "The rack with an eye in it — a server found by name, not by address",
    ["discovery", "find", "registry"], [], ["server discovery", "discover servers", "well-known", "find mcp server"],
    "machine", [...server(), arc(12, 11, 4.5, 200, 340), disc(12, 11, 2)]),
  m("mcp-schema-version", "Schema version", "The rack with a hash in it — which revision of the protocol the server speaks",
    ["schema", "version", "protocol"], [], ["schema version", "protocol version", "spec revision", "version string"],
    "machine", [...server(), col(10, 8, 14), col(14, 8, 14), row(11, 8, 16)]),
  m("mcp-error-code", "Error code", "The rack with a line and a cross under it — the number that says what went wrong",
    ["error", "code", "response"], [], ["error code", "json-rpc error", "error response", "error number"],
    "machine", [...server(), row(8, 9, 15), poly([[10, 11], [14, 15]]), poly([[14, 11], [10, 15]])]),
  m("mcp-retry-policy", "Retry policy", "The rack with chevrons up and down — how a failed call is tried again, and how often",
    ["retry", "policy", "backoff"], [], ["retry policy", "retry with backoff", "retry attempts", "transient errors"],
    "machine", [...server(), poly([[9.5, 9], [12, 6.5], [14.5, 9]]), poly([[9.5, 12.5], [12, 15], [14.5, 12.5]])]),
  m("mcp-tool-timeout", "Tool timeout", "The plug with a clock on it — a tool call given up on after so long",
    ["tool", "timeout", "call"], [], ["tool timeout", "tool call timeout", "slow tool", "call deadline"],
    "figure", [...PLUG(), ...clockMark(SMALL, 15.5)]),

  /* ── Who does what ────────────────────────────────────────────────────────────── */
  orch("agent-router", "Agent router", "The agent ring with one line splitting into two — the request sent to the agent that fits it",
    ["router", "dispatch", "orchestration"], [], ["agent router", "route to agent", "intent routing", "dispatcher"],
    "orbit", [ring(), poly([[7, 12], [10, 12], [13, 9], [16, 9]]), poly([[10, 12], [13, 15], [16, 15]])]),
  orch("agent-supervisor", "Supervisor agent", "The agent ring with one head over two — the agent that hands out work and checks it back in",
    ["supervisor", "hierarchy", "orchestration"], [], ["supervisor agent", "manager agent", "orchestrator", "parent agent"],
    "orbit", [ring(), disc(12, 9, 2), disc(9, 15, 1), disc(15, 15, 1)]),
  orch("agent-worker", "Worker agent", "The agent ring with a hammer in it — the agent that does the piece it was given",
    ["worker", "task", "orchestration"], [], ["worker agent", "sub-agent", "task agent", "child agent"],
    "orbit", [ring(), row(8, 9, 15), col(12, 8, 16)]),
  orch("agent-critic", "Critic agent", "The agent ring with a check and a cross — the agent that says what is wrong with the work",
    ["critic", "review", "orchestration"], [], ["critic agent", "reviewer agent", "critique", "reflection agent"],
    "orbit", [ring(), poly([[7, 12], [9, 14], [12, 11]]), poly([[13.5, 9.5], [16.5, 12.5]]), poly([[16.5, 9.5], [13.5, 12.5]])]),
  orch("agent-planner", "Planner agent", "The agent ring with a staircase in it — the agent that breaks the goal into steps",
    ["planner", "plan", "orchestration"], [], ["planner agent", "planning agent", "task decomposition", "plan steps"],
    "orbit", [ring(), poly([[8, 16], [10.5, 16], [10.5, 13.5], [13, 13.5], [13, 11], [15.5, 11]])]),
  orch("agent-executor", "Executor agent", "The agent ring with a bar and a chevron — the agent that runs the step in front of it",
    ["executor", "run", "orchestration"], [], ["executor agent", "execution agent", "run the plan", "action agent"],
    "orbit", [ring(), col(9, 9, 15), poly([[11.5, 9], [14.5, 12], [11.5, 15]])]),
  orch("agent-verifier", "Verifier agent", "The agent ring with a check in it — the agent that confirms the work is right",
    ["verifier", "check", "orchestration"], [], ["verifier agent", "verification agent", "checker", "validate output"],
    "orbit", [ring(), ...check(SMALL, 12)]),
  orch("agent-blackboard", "Blackboard", "The agent ring with lines on a board — the shared place agents write what they know",
    ["blackboard", "shared", "orchestration"], [], ["blackboard", "blackboard architecture", "shared workspace", "common board"],
    "orbit", [ring(), row(9, 8, 16), row(12.5, 8, 16), row(16, 8, 13)]),
  orch("agent-contract", "Agent contract", "The agent ring with a signature in it — what one agent promised another",
    ["contract", "agreement", "orchestration"], [], ["agent contract", "contract net", "task agreement", "commitment"],
    "orbit", [ring(), poly([[8.5, 14], [11, 11.5], [13.5, 14], [16, 11.5]])]),
  orch("agent-bid", "Agent bid", "The agent ring with a raised chevron over a bar — an agent offering to take the task",
    ["bid", "offer", "orchestration"], [], ["agent bid", "task bidding", "contract net bid", "offer to take task"],
    "orbit", [ring(), poly([[9.5, 11.5], [12, 9], [14.5, 11.5]]), row(14, 9, 15)]),
  orch("agent-vote", "Agent vote", "The agent ring with a check dropped into a slot — each agent's say, counted",
    ["vote", "ballot", "orchestration"], [], ["agent vote", "majority vote", "voting agents", "ballot"],
    "orbit", [ring(), poly([[9, 11], [11, 13], [15, 9]]), row(15.5, 8, 16)]),
  orch("agent-consensus", "Agent consensus", "The agent ring with two checks — agents that came to the same answer",
    ["consensus", "agree", "orchestration"], [], ["agent consensus", "agreement between agents", "consensus reached", "converged"],
    "orbit", [ring(), poly([[8, 10], [10, 12], [13, 9]]), poly([[11, 14], [13, 16], [16, 13]])]),

  /* ── How far it may go ────────────────────────────────────────────────────────── */
  run("agent-fallback", "Agent fallback", "The agent ring with a chevron against a bar — when the first approach fails, the simpler one runs",
    ["fallback", "recover", "run"], [], ["agent fallback", "fallback strategy", "plan b", "degrade gracefully"],
    "orbit", [ring(), col(9, 9, 15), poly([[15, 9], [12, 12], [15, 15]])]),
  run("agent-timeout", "Agent timeout", "The agent ring with an hourglass between two lines — a run stopped for taking too long",
    ["timeout", "limit", "run"], [], ["agent timeout", "run timeout", "wall clock limit", "time limit"],
    "orbit", [ring(), row(8.5, 9, 15), poly([[9, 9], [15, 15]]), poly([[15, 9], [9, 15]]), row(15.5, 9, 15)]),
  run("agent-budget", "Agent budget", "The agent ring with bars on a base — what the run has spent so far, against what it may",
    ["budget", "spend", "run"], [], ["agent budget", "run budget", "spend limit", "token allowance"],
    "orbit", [ring(), row(15, 8, 16), col(9, 10, 15), col(12, 8, 15), col(15, 12, 15)]),
  run("agent-trace", "Agent trace", "The agent ring with a trail of points — the steps a run took, in order",
    ["trace", "steps", "run"], [], ["agent trace", "run trace", "step log", "execution trace"],
    "orbit", [ring(), disc(8, 14, 1), disc(12, 12, 1), disc(16, 10, 1)]),
  run("agent-replay", "Agent replay", "The agent ring with two chevrons back — a run played again from its trace",
    ["replay", "rerun", "run"], [], ["agent replay", "replay run", "re-execute from trace", "rerun"],
    "orbit", [ring(), poly([[11, 9], [8, 12], [11, 15]]), poly([[16, 9], [13, 12], [16, 15]])]),
  run("agent-sandbox-limit", "Sandbox limit", "The agent ring with a floor and a ceiling — the walls an agent's actions stay inside",
    ["sandbox", "limit", "run"], [], ["sandbox limit", "agent sandbox", "restricted environment", "action boundary"],
    "orbit", [ring(), row(8, 8, 16), row(16, 8, 16), col(12, 10, 14)]),
  run("agent-loop-guard", "Loop guard", "The rotation loop with a shield in it — a run stopped before it goes round forever",
    ["loop", "guard", "run"], [], ["loop guard", "infinite loop protection", "max iterations", "cycle detection"],
    "rotation", [...cycle(), ...shieldMark(SMALL, 12)]),
  run("agent-depth-limit", "Depth limit", "The agent ring with an arrow dropping onto a floor — how many agents deep a delegation may go",
    ["depth", "limit", "run"], [], ["depth limit", "max recursion", "delegation depth", "nesting limit"],
    "orbit", [ring(), col(12, 7, 11), poly([[9.5, 9.5], [12, 12], [14.5, 9.5]]), row(15, 8, 16)]),
  run("agent-cost-cap", "Cost cap", "The agent ring with a coin under a lid — the most a run may cost",
    ["cost", "cap", "run"], [], ["cost cap", "spend cap", "max cost per run", "budget ceiling"],
    "orbit", [ring(), row(8, 8, 16), disc(12, 13, 3)]),
  run("agent-interrupt", "Agent interrupt", "The agent ring with a bolt in it — a run broken into from outside",
    ["interrupt", "stop", "run"], [], ["agent interrupt", "interrupt run", "break in", "external stop"],
    "orbit", [ring(), poly([[13.5, 6.5], [9.5, 10.5], [12.5, 10.5], [8.5, 14.5]])]),
  run("agent-resume", "Agent resume", "The agent ring with a play mark in it — a run picked up where it stopped",
    ["resume", "continue", "run"], [], ["agent resume", "resume run", "continue from checkpoint", "pick up"],
    "orbit", [ring(), poly([[10, 8], [10, 16], [14, 12]], true)]),
  run("agent-pulse", "Agent pulse", "The agent ring with a heartbeat in it — the sign, every so often, that the run is still alive",
    ["pulse", "heartbeat", "run"], [], ["agent pulse", "heartbeat", "keepalive", "liveness signal"],
    "orbit", [ring(), poly([[6.5, 12], [9, 12], [11, 10], [13, 12], [15, 10], [17, 12]])]),

  /* ── With tools ───────────────────────────────────────────────────────────────── */
  use("agent-tool-allow", "Tool allowed", "The plug with a chevron let in — a tool this agent may call",
    ["tool", "allow", "permission"], [], ["tool allowed", "allowlist tool", "permitted tool", "tool whitelist"],
    "figure", [...PLUG(), poly([[9, 14], [12, 17], [15, 14]])]),
  use("agent-tool-deny", "Tool denied", "The plug with a bar across it — a tool this agent may not call",
    ["tool", "deny", "permission"], [], ["tool denied", "blocklist tool", "forbidden tool", "tool blacklist"],
    "figure", [...PLUG(), row(15.5, 9, 15)]),
  use("tool-chain", "Tool chain", "The plug with two points tied together — one tool's result fed into the next",
    ["tool", "chain", "sequence"], [], ["tool chain", "chained tools", "tool pipeline", "sequential tools"],
    "figure", [...PLUG(), disc(9, 15.5, 1), row(15.5, 10.5, 13.5), disc(15, 15.5, 1)]),
  use("tool-parallel", "Parallel tools", "The plug with two bars side by side — tools called at the same time",
    ["tool", "parallel", "concurrent"], [], ["parallel tools", "parallel tool calls", "concurrent tools", "fan-out calls"],
    "figure", [...PLUG(), col(9.5, 13, 18), col(14.5, 13, 18)]),
  use("tool-result-cache", "Tool result cache", "The plug with a bolt on it — the same call answered from last time",
    ["tool", "cache", "result"], [], ["tool result cache", "cached tool call", "memoised tool", "cache tool output"],
    "figure", [...PLUG(), BOLT(13.5, 13)]),
  use("tool-error-retry", "Tool error retry", "The plug with chevrons up and down — a tool call that failed, tried again",
    ["tool", "retry", "error"], [], ["tool error retry", "retry tool call", "tool failure recovery", "try again"],
    "figure", [...PLUG(), poly([[9.5, 14.5], [12, 12], [14.5, 14.5]]), poly([[9.5, 16.5], [12, 19], [14.5, 16.5]])]),
];
