/**
 * R19 · RAG & knowledge depth — how a document is cut, how a question is asked, how the
 * pieces are found, and how well.
 *
 * A piece of a document is on the page. What is filtered goes through the funnel, and
 * what came through sits under its stem. A vector lives in the lattice `embedding` stands
 * in. A question, and the measure of how well it was answered, sits in the lens
 * `vector-search` looks through.
 */
import { arc, col, disc, poly, rect, row } from "../forms.ts";
import { funnel, lattice, page } from "../bodies.ts";
import { SMALL, add, listMark, off, squareMark, tagMark } from "../marks.ts";
import type { Icon } from "../build.ts";

const c = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({
  slug, category: "rag", subcategory: "retrieval", name, description,
  tags, aliases, keywords, family, shapes,
});

/** The lens `vector-search` looks through: a ring centred on (10, 10) and its handle. Content stays within 5.5 of the centre. */
const LENS = () => [arc(10, 10, 7, 292, 248), poly([[15, 15], [21, 21]])];
/** The set's bolt, 2.5 wide, with its top-right corner at (x, y). */
const BOLT = (x: number, y: number) => poly([[x, y], [x - 2.5, y + 2.5], [x, y + 2.5], [x - 2.5, y + 5]]);

export const BATCH_106: Icon[] = [
  /* ── On the page ──────────────────────────────────────────────────────────────── */
  c("recursive-chunk", "Recursive chunking", "A page with lines that step in — a document split, and the pieces split again",
    ["chunk", "recursive", "split"], [], ["recursive chunking", "recursive text splitter", "split by separators", "nested chunks"],
    "page", [page(), row(9, 8, 16), row(12, 10, 16), row(15, 12, 16)]),
  c("sentence-window", "Sentence window", "A page with posts through the middle line — a sentence kept with the ones around it",
    ["chunk", "window", "sentence"], [], ["sentence window", "sentence window retrieval", "surrounding sentences", "context window chunk"],
    "page", [page(), row(9, 8, 16), row(13, 8, 16), row(17, 8, 16), col(9.5, 11, 15), col(14.5, 11, 15)]),
  c("parent-document", "Parent document", "A page with a small box in it — the whole document a chunk came from",
    ["chunk", "parent", "document"], [], ["parent document", "parent document retriever", "return the parent", "chunk to document"],
    "page", [page(), poly([[9.5, 10], [9.5, 16], [14.5, 16], [14.5, 10]], true)]),
  c("contextual-chunk", "Contextual chunk", "A page with a header over a box — a chunk sent with the context that explains it",
    ["chunk", "context", "header"], [], ["contextual chunk", "contextual retrieval", "chunk with context", "situated chunk"],
    "page", [page(), row(8, 8, 15), poly([[9.5, 11], [9.5, 17], [14.5, 17], [14.5, 11]], true)]),
  c("chunk-metadata", "Chunk metadata", "A page with a line and a tag under it — what is known about a chunk besides its text",
    ["chunk", "metadata", "tag"], [], ["chunk metadata", "chunk fields", "source metadata", "chunk attributes"],
    "page", [page(), row(9, 8, 16), ...tagMark(SMALL, 15)]),
  c("citation-span", "Citation span", "A page with a line and a stretch of the next one marked off — exactly which words an answer rests on",
    ["citation", "span", "source"], [], ["citation span", "cited passage", "supporting span", "evidence span"],
    "page", [page(), row(8, 8, 15), row(13, 8, 16), col(9, 11, 15), col(15, 11, 15)]),
  c("passage-merge", "Passage merge", "A page with two lines joining into one — neighbouring chunks stitched back together",
    ["chunk", "merge", "passage"], [], ["passage merge", "merge chunks", "adjacent chunks", "stitch passages"],
    "page", [page(), poly([[8, 9], [10.5, 9], [13, 11.5], [16, 11.5]]), poly([[8, 14], [10.5, 14], [13, 11.5]])]),
  c("source-weight", "Source weight", "A page with a weight on it — how much one source counts against another",
    ["source", "weight", "rank"], [], ["source weight", "source priority", "weighted sources", "source boost"],
    "page", [page(), poly([[8.5, 17], [12, 13.5], [15.5, 17]], true)]),

  /* ── Through the funnel ───────────────────────────────────────────────────────── */
  c("metadata-filter", "Metadata filter", "The funnel with a tag under it — only chunks whose fields match",
    ["filter", "metadata", "search"], [], ["metadata filter", "filter by field", "attribute filter", "filtered search"],
    "funnel", [funnel(), ...tagMark(SMALL, 18)]),
  c("post-filter", "Post-filter", "The funnel with a list under it — the results, thinned after they were found",
    ["filter", "post", "search"], [], ["post-filter", "post-filtering", "filter after search", "filter results"],
    "funnel", [funnel(), ...listMark(SMALL, 18)]),
  c("rerank-window", "Rerank window", "The funnel with brackets under it — the top results, and only those, scored again",
    ["rerank", "window", "search"], [], ["rerank window", "rerank top k", "candidates to rerank", "rerank depth"],
    "funnel", [funnel(), poly([[10.5, 15.5], [8, 15.5], [8, 21], [10.5, 21]]), poly([[13.5, 15.5], [16, 15.5], [16, 21], [13.5, 21]])]),
  c("hybrid-weight", "Hybrid weight", "The funnel with a big and a small weight under it — how much keyword and how much vector",
    ["hybrid", "weight", "search"], [], ["hybrid weight", "alpha weighting", "keyword vs vector weight", "hybrid balance"],
    "funnel", [funnel(), disc(9.5, 18, 2), disc(15, 18, 1)]),
  c("fusion-rank", "Fusion rank", "The funnel with two columns tied by a bar — two result lists folded into one",
    ["fusion", "rank", "search"], [], ["fusion rank", "rank fusion", "merge result lists", "combined ranking"],
    "funnel", [funnel(), col(9, 15.5, 20.5), row(18, 10.5, 13.5), col(15, 15.5, 20.5)]),
  c("reciprocal-fusion", "Reciprocal rank fusion", "The funnel with an arrow pointing both ways — each list's ranks traded into one score",
    ["fusion", "reciprocal", "rank"], [], ["reciprocal rank fusion", "rrf", "rank-based fusion", "combine rankings"],
    "funnel", [funnel(), row(18, 8, 16), poly([[10.5, 15.5], [8, 18], [10.5, 20.5]]), poly([[13.5, 15.5], [16, 18], [13.5, 20.5]])]),
  c("retrieval-fallback", "Retrieval fallback", "The funnel with an arrow pointing back — when nothing good is found, the plainer search runs",
    ["fallback", "search", "retry"], [], ["retrieval fallback", "fallback search", "second-pass retrieval", "broaden search"],
    "funnel", [funnel(), row(18, 9, 15), poly([[11.5, 15.5], [9, 18], [11.5, 20.5]])]),

  /* ── In the lattice ───────────────────────────────────────────────────────────── */
  c("sparse-vector", "Sparse vector", "The lattice with one point over an empty line — a vector that is mostly zeros",
    ["vector", "sparse", "embedding"], [], ["sparse vector", "sparse embedding", "bm25 vector", "mostly zeros"],
    "lattice", [lattice(), disc(12, 10.5, 1), row(14.5, 9, 15)]),
  c("dense-vector", "Dense vector", "The lattice with two full lines — a vector with something in every dimension",
    ["vector", "dense", "embedding"], [], ["dense vector", "dense embedding", "neural embedding", "every dimension set"],
    "lattice", [lattice(), row(11, 9, 15), row(14.5, 9, 15)]),
  c("late-interaction", "Late interaction", "The lattice with two points tied together — query and document matched token by token, at the end",
    ["vector", "late-interaction", "match"], [], ["late interaction", "token-level matching", "maxsim", "late fusion"],
    "lattice", [lattice(), disc(8.5, 13, 1), row(13, 10.5, 13.5), disc(15.5, 13, 1)]),
  c("colbert", "ColBERT", "The lattice with three bars side by side — one vector per token, kept apart",
    ["vector", "colbert", "model"], [], ["colbert", "colbertv2", "multi-vector", "per-token embeddings"],
    "lattice", [lattice(), col(9, 10.5, 15.5), col(12, 10.5, 15.5), col(15, 10.5, 15.5)]),
  c("splade", "SPLADE", "The lattice with a wisp in it — a sparse vector the model learned to expand",
    ["vector", "splade", "model"], [], ["splade", "learned sparse", "term expansion", "sparse lexical"],
    "lattice", [lattice(), poly([[8.5, 14.5], [11, 12], [13.5, 14.5], [16, 12]])]),
  c("bi-encoder", "Bi-encoder", "The lattice with two towers side by side — query and document embedded apart, compared after",
    ["vector", "bi-encoder", "model"], [], ["bi-encoder", "dual encoder", "two-tower", "separate encoders"],
    "lattice", [lattice(), col(9.5, 10.5, 15.5), col(14.5, 10.5, 15.5)]),
  c("query-embed", "Query embedding", "The lattice with an arrow in it — a question turned into a vector",
    ["query", "embedding", "vector"], [], ["query embedding", "embed the query", "question vector", "query encoder"],
    "lattice", [lattice(), poly([[9, 15], [14, 10]]), poly([[11.5, 10], [14, 10], [14, 12.5]])]),
  c("delete-vector", "Delete vector", "The lattice with a cross in it — a vector taken out of the index",
    ["vector", "delete", "index"], [], ["delete vector", "remove embedding", "delete from index", "vector removal"],
    "lattice", [lattice(), ...off(SMALL, 13)]),
  c("namespace-vector", "Vector namespace", "The lattice with brackets in it — vectors kept apart by whose they are",
    ["vector", "namespace", "index"], [], ["vector namespace", "index namespace", "partitioned vectors", "per-tenant vectors"],
    "lattice", [lattice(), poly([[11, 10], [8.5, 10], [8.5, 15], [11, 15]]), poly([[13, 10], [15.5, 10], [15.5, 15], [13, 15]])]),
  c("collection-vector", "Vector collection", "The lattice with a box in it — the set of vectors an index holds",
    ["vector", "collection", "index"], [], ["vector collection", "collection", "vector set", "index collection"],
    "lattice", [lattice(), ...squareMark(SMALL, 12)]),
  c("similarity-cosine", "Cosine similarity", "The lattice with two rays from one point — how close two vectors point",
    ["similarity", "cosine", "vector"], [], ["cosine similarity", "cosine distance", "angle between vectors", "cosine score"],
    "lattice", [lattice(), poly([[9, 15], [15, 15]]), poly([[9, 15], [13.5, 10.5]])]),
  c("similarity-dot", "Dot product", "The lattice with a vector and its shadow on the axis — how far one vector reaches along another",
    ["similarity", "dot", "vector"], [], ["dot product", "inner product", "dot similarity", "unnormalised similarity"],
    "lattice", [lattice(), row(14.5, 8, 16), poly([[9, 14.5], [13.5, 10]]), col(13.5, 10, 14.5)]),
  c("similarity-euclidean", "Euclidean distance", "The lattice with two points and the straight line between — how far apart two vectors sit",
    ["similarity", "euclidean", "vector"], [], ["euclidean distance", "l2 distance", "straight-line distance", "distance metric"],
    "lattice", [lattice(), disc(9, 15.5, 1), disc(15, 9.5, 1), poly([[10, 14.5], [14, 10.5]])]),
  c("quantise-vector", "Quantise vector", "The lattice with a staircase in it — a vector stored in fewer bits",
    ["vector", "quantise", "compress"], [], ["quantise vector", "scalar quantisation", "int8 vectors", "binary quantisation"],
    "lattice", [lattice(), poly([[8.5, 15], [11, 15], [11, 12.5], [13.5, 12.5], [13.5, 10], [16, 10]])]),
  c("product-quantisation", "Product quantisation", "The lattice cut into strips — a vector split into parts, each stored as a code",
    ["vector", "quantise", "pq"], [], ["product quantisation", "pq", "sub-vector codes", "ivf-pq"],
    "lattice", [lattice(), col(10.5, 10, 16), col(13.5, 10, 16)]),
  c("hnsw-graph", "HNSW graph", "The lattice with a tree in it — layers of links, coarse on top and fine below",
    ["index", "hnsw", "graph"], [], ["hnsw graph", "hierarchical navigable small world", "graph index", "ann graph"],
    "lattice", [lattice(), poly([[9, 15], [12, 12], [15, 15]]), col(12, 8.5, 12)]),
  c("ivf-list", "IVF list", "The lattice with a centroid between two walls — vectors grouped into cells, each with its list",
    ["index", "ivf", "cluster"], [], ["ivf list", "inverted file index", "ivf cells", "coarse quantiser"],
    "lattice", [lattice(), col(9, 10, 15), col(15, 10, 15), disc(12, 12.5, 1)]),
  c("retrieval-cache", "Retrieval cache", "The lattice with a bolt in it — a query answered from what was fetched last time",
    ["cache", "retrieval", "search"], [], ["retrieval cache", "semantic cache", "cached retrieval", "cache hits"],
    "lattice", [lattice(), BOLT(13.5, 10)]),
  c("index-refresh", "Index refresh", "The lattice with an arrow looping back — the index rebuilt from the source",
    ["index", "refresh", "rebuild"], [], ["index refresh", "reindex", "rebuild vectors", "refresh embeddings"],
    "lattice", [lattice(), poly([[9, 15], [9, 10], [15, 10], [15, 15]]), poly([[12.5, 12.5], [15, 15], [17.5, 12.5]])]),
  c("index-snapshot", "Index snapshot", "The lattice with an eye in it — the index as it was at one moment, kept",
    ["index", "snapshot", "backup"], [], ["index snapshot", "vector index backup", "point-in-time index", "index copy"],
    "lattice", [lattice(), arc(12, 13, 4, 200, 340), disc(12, 13, 2)]),
  c("incremental-index", "Incremental index", "The lattice with a plus in it — new vectors added without rebuilding the rest",
    ["index", "incremental", "update"], [], ["incremental index", "incremental indexing", "upsert vectors", "add to index"],
    "lattice", [lattice(), ...add(SMALL, 13)]),
  c("retrieval-depth", "Retrieval depth", "The lattice with an arrow going down — how far down the ranking the search reads",
    ["search", "depth", "top-k"], [], ["retrieval depth", "search depth", "candidates fetched", "ef search"],
    "lattice", [lattice(), col(12, 9, 17), poly([[9.5, 14.5], [12, 17], [14.5, 14.5]])]),

  /* ── In the lens ──────────────────────────────────────────────────────────────── */
  c("query-rewrite", "Query rewrite", "The lens with a pencil stroke in it — the question reworded before it is searched",
    ["query", "rewrite", "search"], [], ["query rewrite", "query rewriting", "rephrase query", "query transformation"],
    "magnifier", [...LENS(), poly([[7, 13], [13, 7]])]),
  c("query-decompose", "Query decomposition", "The lens with one line splitting into two — a question broken into the questions inside it",
    ["query", "decompose", "search"], [], ["query decomposition", "split question", "decompose query", "multi-part question"],
    "magnifier", [...LENS(), poly([[5.5, 10], [8, 10], [10.5, 7.5], [13, 7.5]]), poly([[8, 10], [10.5, 12.5], [13, 12.5]])]),
  c("sub-question", "Sub-question", "The lens with a question mark in it — one of the smaller questions a big one breaks into",
    ["query", "sub-question", "search"], [], ["sub-question", "sub query", "sub-question engine", "follow-up question"],
    "magnifier", [...LENS(), arc(10, 8, 2.5, 180, 90), disc(10, 13, 1)]),
  c("step-back-prompt", "Step-back prompt", "The lens with a chevron rising over a line — the broader question asked first",
    ["query", "step-back", "prompt"], [], ["step-back prompt", "step-back prompting", "abstract the question", "broader query"],
    "magnifier", [...LENS(), poly([[7.5, 11], [10, 8.5], [12.5, 11]]), row(13.5, 7, 13)]),
  c("multi-query", "Multi-query", "The lens with three lines in it — the same question asked several ways",
    ["query", "multi", "search"], [], ["multi-query", "query variants", "several phrasings", "multi-query retriever"],
    "magnifier", [...LENS(), row(7, 7, 13), row(10, 7, 13), row(13, 7, 13)]),
  c("recall-at-k", "Recall@k", "The lens with a check in it — how much of what should be found is in the top results",
    ["metric", "recall", "search"], [], ["recall at k", "recall@k", "retrieval recall", "found in top k"],
    "magnifier", [...LENS(), poly([[7, 10], [9, 12], [13, 8]])]),
  c("precision-at-k", "Precision@k", "The lens with a ring in it — how much of the top results is worth having",
    ["metric", "precision", "search"], [], ["precision at k", "precision@k", "retrieval precision", "relevant in top k"],
    "magnifier", [...LENS(), disc(10, 10, 3)]),
  c("ndcg", "NDCG", "The lens with bars stepping down — results graded by how good they are and how high they sit",
    ["metric", "ndcg", "rank"], [], ["ndcg", "normalised discounted cumulative gain", "graded relevance", "ranking metric"],
    "magnifier", [...LENS(), col(7, 7, 13), col(10, 9, 13), col(13, 10.5, 13)]),
  c("mrr", "MRR", "The lens with a point ahead of a line — how high up the first right answer sits",
    ["metric", "mrr", "rank"], [], ["mrr", "mean reciprocal rank", "first relevant result", "rank of first hit"],
    "magnifier", [...LENS(), disc(7.5, 10, 1), row(10, 9.5, 13)]),
  c("context-relevance", "Context relevance", "The lens with brackets in it — whether what was fetched was worth fetching",
    ["metric", "relevance", "context"], [], ["context relevance", "retrieved context relevance", "ragas context relevance", "useful context"],
    "magnifier", [...LENS(), poly([[8.5, 7], [6, 7], [6, 13], [8.5, 13]]), poly([[11.5, 7], [14, 7], [14, 13], [11.5, 13]])]),
  c("answer-relevance", "Answer relevance", "The lens with a speech bubble in it — whether the answer speaks to the question",
    ["metric", "relevance", "answer"], [], ["answer relevance", "answer relevancy", "on-topic answer", "ragas answer relevance"],
    "magnifier", [...LENS(), poly([[7, 7], [13, 7], [13, 11], [9.5, 11], [7, 13.5]], true)]),
  c("faithfulness", "Faithfulness", "The lens with a shield in it — whether the answer says only what the sources say",
    ["metric", "faithfulness", "grounding"], [], ["faithfulness", "answer faithfulness", "grounded in sources", "ragas faithfulness"],
    "magnifier", [...LENS(), poly([[7, 7], [13, 7], [13, 11], [10, 14], [7, 11]], true)]),
  c("retrieval-eval", "Retrieval evaluation", "The lens with a check and a cross in it — the hits and the misses, counted",
    ["metric", "evaluation", "search"], [], ["retrieval evaluation", "retrieval eval", "search quality", "retriever benchmark"],
    "magnifier", [...LENS(), poly([[6.5, 10], [8.5, 12], [11, 9.5]]), poly([[10, 7], [14, 11]]), poly([[14, 7], [10, 11]])]),
];
