/**
 * R43 · Health: nutrition & body — what goes on the plate, and what the body does with it.
 *
 * The food is drawn as itself: an apple, a banana, a carrot with its leaves, broccoli, a
 * bowl of greens, a bread slice, a wheat ear, sugar cubes, a shaker, a jar, a carton, a
 * smoothie, a chocolate bar. The plate is a ring the round can vary. The body end of the
 * round measures: a scale, a tape, a height between two lines, a fingertip, a head of hair.
 */
import { arc, col, disc, poly, raw, rect, row } from "../forms.ts";
import type { Icon } from "../build.ts";

const c = (
  slug: string, name: string, description: string,
  tags: string[], aliases: string[], keywords: string[],
  family: string, shapes: Icon["shapes"],
): Icon => ({
  slug, category: "health", subcategory: "nutrition", name, description,
  tags, aliases, keywords, family, shapes,
});

/** The plate seen from above: a rim and the well inside it. */
const PLATE = () => [disc(12, 12, 9), disc(12, 12, 5)];
/** The bowl: a rim with the round belly under it. */
const BOWL = () => [row(11, 2, 22), arc(12, 11, 9, 0, 180)];
/** The wheat ear: a stalk with grains springing off it. */
const WHEAT = () => [
  col(12, 4, 20), poly([[12, 9], [8, 5]]), poly([[12, 9], [16, 5]]),
  poly([[12, 14], [8, 10]]), poly([[12, 14], [16, 10]]),
];
/** A drop, for the fats and the water. */
const DROP = (x: number, y: number, r: number) => raw(
  `M${x} ${y - r}L${x + r} ${y}A${r} ${r} 0 1 1 ${x - r} ${y}Z`,
  "a drop: a point over a round belly", true,
);

export const BATCH_130: Icon[] = [
  /* ── the food ───────────────────────────────────────────────────────────────── */
  c("apple", "Apple", "The apple with its stalk",
    ["apple", "fruit", "fresh"], [], ["apple", "fruit", "an apple a day", "fresh fruit"],
    "apple", [raw("M12 9C9 5 4 7 4 13C4 18 8 21 12 19C16 21 20 18 20 13C20 7 15 5 12 9Z", "an apple: two shoulders meeting in a dimple", true), poly([[12, 9], [12, 4]])]),
  c("banana", "Banana", "The banana curving away",
    ["banana", "fruit", "peel"], [], ["banana", "fruit", "bananas", "peel"],
    "banana", [raw("M4 7C4 16 10 21 20 19C13 17 9 13 9 6Z", "a banana: a long crescent with a stub of stalk", true)]),
  c("carrot", "Carrot", "The root lying with its greens",
    ["carrot", "root", "veg"], [], ["carrot", "root vegetable", "veg", "carrots"],
    "carrot", [raw("M9 8H15C15 13 13 19 12 21C11 19 9 13 9 8Z", "the root, tapering to its tip", true), poly([[9, 8], [5, 4]]), poly([[12, 8], [12, 3]]), poly([[15, 8], [19, 4]])]),
  c("broccoli", "Broccoli", "The florets over the stalk and its shoots",
    ["broccoli", "green", "veg"], [], ["broccoli", "green vegetable", "veg", "florets"],
    "broccoli", [raw("M5 13A4 4 0 0 1 9 7A4 4 0 0 1 15 7A4 4 0 0 1 19 13Z", "the head, bumped along the top", true), poly([[12, 13], [12, 20]]), poly([[12, 16], [8, 16]]), poly([[12, 16], [16, 16]])]),
  c("salad", "Salad", "The leaves standing out of the bowl",
    ["salad", "leaves", "greens"], [], ["salad", "green salad", "leaves", "a bowl of greens"],
    "figure", [...BOWL(), poly([[5, 11], [9, 7], [13, 11]]), poly([[11, 11], [15, 7], [19, 11]])]),
  c("meal", "Meal", "The plate with the food on it",
    ["meal", "dish", "food"], ["dish"], ["meal", "a meal", "dish", "dinner"],
    "plate", [disc(12, 12, 9), arc(12, 15, 5, 180, 360)]),
  c("plate", "Plate", "The plate laid with its knife and fork",
    ["plate", "empty", "table"], [], ["plate", "empty plate", "dinner plate", "tableware"],
    "plate", [disc(12, 12, 6), col(4, 4, 20), col(20, 4, 20)]),
  c("portion", "Portion", "The bowl filled to the line",
    ["portion", "half", "share"], ["serving"], ["portion", "serving", "portion size", "half the plate"],
    "figure", [row(8, 2, 22), arc(12, 8, 9, 0, 180), row(12, 5, 19)]),
  c("carbohydrate", "Carbohydrate", "The slice of bread",
    ["carbs", "bread", "starch"], ["carbs"], ["carbohydrate", "carbs", "bread", "starch"],
    "bread", [raw("M5 20V11A4 4 0 0 1 9 7H15A4 4 0 0 1 19 11V20Z", "a slice: a domed crust over a square crumb", true)]),
  c("fibre", "Fibre", "The ear of wheat",
    ["fibre", "grain", "whole"], ["fiber"], ["fibre", "fiber", "wholegrain", "roughage"],
    "wheat", WHEAT()),
  c("fat", "Fat", "The pat of butter",
    ["fat", "butter", "oil"], [], ["fat", "fats", "butter", "oil"],
    "block", [poly([[3, 12], [8, 7], [21, 7], [21, 12], [16, 17], [3, 17]], true)]),
  c("sugar", "Sugar", "Two cubes of sugar",
    ["sugar", "cube", "sweet"], [], ["sugar", "sugar cube", "sweet", "sugars"],
    "cube", [poly([[3, 11], [11, 11], [11, 19], [3, 19]], true), poly([[13, 5], [21, 5], [21, 13], [13, 13]], true)]),
  c("salt", "Salt", "The shaker over the grains",
    ["salt", "shaker", "season"], ["sodium"], ["salt", "sodium", "salt shaker", "seasoning"],
    "shaker", [poly([[8, 21], [8, 11], [10, 9], [14, 9], [16, 11], [16, 21]], true), row(13, 8, 16), disc(10, 5, 1), disc(14, 6, 1)]),
  c("snack", "Snack", "The bar broken into squares",
    ["snack", "bar", "bite"], [], ["snack", "snack bar", "a bite", "between meals"],
    "bar", [rect(4, 7, 16, 10, 2), col(9, 7, 17), col(14, 7, 17)]),

  /* ── the drinks ─────────────────────────────────────────────────────────────── */
  c("coffee-cup", "Coffee", "The cup on its saucer",
    ["coffee", "cup", "hot"], [], ["coffee", "a coffee", "cup of coffee", "espresso"],
    "cup", [poly([[4, 7], [4, 16], [15, 16], [15, 7]]), arc(15, 10, 3, 270, 90), row(19, 2, 17)]),
  c("tea-cup", "Tea", "The cup with the bag hanging in it",
    ["tea", "cup", "brew"], ["brew"], ["tea", "a cup of tea", "brew", "tea bag"],
    "cup", [poly([[5, 9], [5, 18], [16, 18], [16, 9]]), poly([[10, 9], [10, 5]]), poly([[8, 2], [13, 2], [13, 5], [8, 5]], true)]),
  c("juice", "Juice", "The carton with a straw in it",
    ["juice", "carton", "drink"], [], ["juice", "fruit juice", "carton", "a drink"],
    "carton", [poly([[6, 8], [6, 21], [16, 21], [16, 8]], true), poly([[6, 8], [11, 3], [16, 8]]), poly([[13, 8], [18, 3]])]),
  c("smoothie", "Smoothie", "The glass with the fruit heaped on top",
    ["smoothie", "blend", "glass"], [], ["smoothie", "blended drink", "shake", "fruit drink"],
    "glass", [poly([[8, 8], [8, 20], [16, 20], [16, 8]]), arc(12, 8, 4, 180, 360), poly([[14, 6], [18, 2]])]),
  c("water-intake", "Water intake", "The drop going into the glass",
    ["water", "intake", "drink"], [], ["water intake", "drink water", "how much water", "fluids"],
    "glass", [poly([[7, 11], [7, 17], [10, 20], [14, 20], [17, 17], [17, 11]]), DROP(12, 6, 3.5)]),
  c("measuring-cup", "Measuring jug", "The jug with its marks",
    ["jug", "measure", "marks"], ["jug"], ["measuring jug", "measuring cup", "measure", "marks"],
    "jug", [poly([[5, 6], [5, 19], [17, 19], [17, 6]]), row(11, 6, 12), row(15, 6, 12), arc(17, 12, 3, 270, 90)]),
  c("fork-knife", "Knife and fork", "The two laid out",
    ["cutlery", "fork", "knife"], ["cutlery"], ["knife and fork", "cutlery", "eat", "place setting"],
    "cutlery", [col(5, 3, 8), col(9, 3, 8), row(8, 5, 9), col(7, 8, 21), poly([[16, 4], [19, 7], [19, 13], [16, 13]], true), col(17.5, 13, 21)]),
  c("spoon", "Spoon", "The bowl of the spoon and its handle",
    ["spoon", "stir", "scoop"], [], ["spoon", "a spoon", "stir", "teaspoon"],
    "spoon", [raw("M8 5A4 4 0 0 1 16 5C16 10 14 13 12 13C10 13 8 10 8 5Z", "the bowl of the spoon, narrowing into the handle", true), poly([[12, 13], [12, 21]])]),

  /* ── what it is made of ─────────────────────────────────────────────────────── */
  c("calorie", "Calorie", "The flame the food carries",
    ["calorie", "energy", "kcal"], [], ["calorie", "calories", "kcal", "energy in food"],
    "figure", [raw("M12 3C13.5 6 16 7 16 10A4 4 0 1 1 8 10C8 7.5 10 7 10 5.5C10.5 6.5 12 6.5 12 3Z", "a flame: the tongue curling up from a round belly", true), row(16, 4, 20), arc(12, 16, 6, 0, 180)]),
  c("macronutrient", "Macronutrients", "The three bands of a diet",
    ["macros", "split", "bands"], ["macros"], ["macronutrients", "macros", "protein carbs fat", "split"],
    "stack", [rect(3, 7, 18, 10, 2), row(10.5, 3, 21), row(13.5, 3, 21)]),
  c("vitamin", "Vitamin", "The capsule with the plus beside it",
    ["vitamin", "capsule", "boost"], [], ["vitamin", "vitamins", "capsule", "supplement pill"],
    "pill", [raw("M4 13L10 7A4 4 0 0 1 15 12L9 18A4 4 0 0 1 4 13Z", "a capsule: two rounded ends on the diagonal", true), col(19, 4, 10), row(7, 16, 22)]),
  c("supplement", "Supplement", "The tub with its lid",
    ["supplement", "tub", "powder"], [], ["supplement", "supplements", "tub", "powder"],
    "jar", [poly([[6, 21], [6, 9], [18, 9], [18, 21]], true), poly([[5, 9], [5, 6], [19, 6], [19, 9]])]),
  c("nutrition-label", "Nutrition label", "The panel on the back of the pack",
    ["label", "panel", "pack"], [], ["nutrition label", "nutrition panel", "back of pack", "label"],
    "page", [rect(4, 3, 16, 18, 2), row(8, 7, 17), row(12, 7, 17), row(16, 7, 13)]),
  c("meal-plan", "Meal plan", "The week with a meal on it",
    ["plan", "week", "menu"], [], ["meal plan", "menu", "weekly meals", "plan meals"],
    "window", [rect(3, 5, 18, 16, 2), row(9, 3, 21), col(8, 2, 5), col(16, 2, 5), disc(12, 15, 3)]),
  c("meal-log", "Meal log", "The sheet with the meal written down",
    ["log", "record", "diary"], ["food-diary"], ["meal log", "food diary", "log a meal", "record"],
    "page", [rect(4, 3, 16, 18, 2), disc(12, 8, 3), row(14, 8, 16), row(17, 8, 13)]),
  c("diet", "Diet", "The plate with the leaf on it",
    ["diet", "eating", "plan"], [], ["diet", "eating plan", "on a diet", "healthy eating"],
    "plate", [disc(12, 12, 9), raw("M8 15C8 11 11 8 16 8C16 13 13 16 8 15Z", "a leaf on the plate", true)]),
  c("fasting", "Fasting", "The fork struck through",
    ["fast", "skip", "empty"], [], ["fasting", "fast", "skip a meal", "not eating"],
    "cutlery", [col(9, 4, 7), col(15, 4, 7), row(7, 9, 15), col(12, 7, 20), poly([[4, 20], [16, 8]])]),
  c("fasting-window", "Fasting window", "The hours you eat between",
    ["window", "hours", "span"], ["eating-window"], ["fasting window", "eating window", "hours", "time restricted"],
    "timeline", [poly([[6, 7], [3, 7], [3, 17], [6, 17]]), poly([[18, 7], [21, 7], [21, 17], [18, 17]]), row(12, 7, 17)]),

  /* ── what you can and cannot eat ────────────────────────────────────────────── */
  c("vegetarian", "Vegetarian", "The leaf on the fork",
    ["vegetarian", "meat-free", "leaf"], ["veggie"], ["vegetarian", "veggie", "meat free", "no meat"],
    "cutlery", [col(6, 3, 8), col(10, 3, 8), row(8, 6, 10), col(8, 8, 21), raw("M14 18C14 13 17 10 22 10C22 15 19 18 14 18Z", "a leaf beside the fork", true)]),
  c("vegan", "Vegan", "The sprout with two leaves",
    ["vegan", "plant", "sprout"], ["plant-based"], ["vegan", "plant based", "sprout", "no animal products"],
    "sprout", [poly([[12, 21], [12, 13]]), raw("M12 13C12 8 8 5 3 5C3 10 7 13 12 13Z", "a leaf on the left", true), raw("M12 13C12 8 16 5 21 5C21 10 17 13 12 13Z", "a leaf on the right", true)]),
  c("gluten-free", "Gluten free", "The wheat struck out",
    ["gluten", "wheat", "free"], ["no-gluten"], ["gluten free", "no gluten", "coeliac", "wheat free"],
    "wheat", [...WHEAT(), poly([[4, 20], [20, 4]])]),
  c("dairy-free", "Dairy free", "The carton struck out",
    ["dairy", "milk", "free"], ["no-dairy"], ["dairy free", "no dairy", "lactose free", "milk free"],
    "carton", [poly([[7, 9], [7, 20], [16, 20], [16, 9]], true), poly([[7, 9], [11.5, 4.5], [16, 9]]), poly([[4, 21], [20, 5]])]),
  c("allergen", "Allergen", "The bowl under a warning",
    ["allergen", "warning", "care"], [], ["allergen", "allergens", "allergy warning", "may contain"],
    "figure", [row(11, 2, 22), arc(12, 11, 9, 0, 180), raw("M12 2L19 9H5Z", "a warning triangle over the bowl", true)]),
  c("nut-allergy", "Nut allergy", "The nut struck out",
    ["nut", "allergy", "avoid"], [], ["nut allergy", "nuts", "peanut allergy", "avoid nuts"],
    "nut", [raw("M12 3C16 6 18 10 18 14A6 6 0 0 1 6 14C6 10 8 6 12 3Z", "a nut: a point over a round shell", true), poly([[6, 19], [18, 7]])]),
  c("shellfish-allergy", "Shellfish allergy", "The shell struck out",
    ["shellfish", "allergy", "avoid"], [], ["shellfish allergy", "shellfish", "seafood allergy", "avoid shellfish"],
    "shell", [raw("M4 18A8 8 0 0 1 20 18Z", "a fan shell, flat along the hinge", true), poly([[5, 20], [19, 6]])]),

  /* ── the body it feeds ──────────────────────────────────────────────────────── */
  c("body-scale", "Bathroom scales", "The scales with a place for each foot",
    ["scales", "weigh", "dial"], ["scales"], ["bathroom scales", "weigh yourself", "scales", "weight"],
    "scale", [rect(3, 6, 18, 13, 2), poly([[7, 10], [10, 10], [10, 16], [7, 16]], true), poly([[14, 10], [17, 10], [17, 16], [14, 16]], true)]),
  c("weight-goal", "Weight goal", "The scales with the target over them",
    ["weight", "goal", "target"], [], ["weight goal", "target weight", "goal", "aim"],
    "scale", [rect(3, 12, 18, 8, 2), poly([[12, 12], [12, 3]]), poly([[12, 3], [19, 3], [19, 8], [12, 8]])]),
  c("bmi", "BMI", "The figure inside the frame",
    ["bmi", "index", "range"], ["body-mass-index"], ["bmi", "body mass index", "weight for height", "range"],
    "window", [rect(3, 3, 18, 18, 2), disc(12, 8, 2), poly([[12, 10], [12, 14]]), poly([[9, 17], [12, 14], [15, 17]])]),
  c("body-fat", "Body fat", "The figure beside the drop",
    ["body", "fat", "percent"], [], ["body fat", "body fat percentage", "fat mass", "composition"],
    "person", [disc(6, 7, 3), arc(6.5, 16, 4.5, 180, 360), DROP(17, 13, 5)]),
  c("waist-measure", "Waist measure", "The tape with its marks",
    ["waist", "tape", "middle"], [], ["waist measure", "waist size", "tape measure", "round the middle"],
    "tape", [row(7, 2, 22), row(17, 2, 22), col(6, 7, 11), col(12, 7, 11), col(18, 7, 11)]),
  c("height-measure", "Height", "The span between floor and crown",
    ["height", "span", "tall"], [], ["height", "how tall", "measure height", "stature"],
    "span", [poly([[12, 3], [12, 21]]), poly([[9, 6], [12, 3], [15, 6]]), poly([[9, 18], [12, 21], [15, 18]]), row(3, 6, 18), row(21, 6, 18)]),
  c("body-temperature", "Body temperature", "The thermometer with the heat coming off it",
    ["temperature", "fever", "degrees"], [], ["body temperature", "fever", "temperature check", "degrees"],
    "figure", [col(9, 4, 15), disc(9, 18, 3), arc(15, 10, 3, 270, 90), arc(15, 10, 6, 270, 90)]),
  c("skin", "Skin", "The patch and the layers under it",
    ["skin", "patch", "grain"], [], ["skin", "skin health", "complexion", "patch of skin"],
    "window", [rect(4, 4, 16, 16, 2), poly([[7, 9], [10, 12], [13, 9], [16, 12]]), poly([[7, 14], [10, 17], [13, 14], [16, 17]])]),
  c("hair", "Hair", "The comb you run through it",
    ["hair", "strands", "scalp"], [], ["hair", "hair health", "strands", "scalp"],
    "comb", [poly([[3, 6], [21, 6], [21, 11], [3, 11]], true), col(7, 11, 19), col(12, 11, 19), col(17, 11, 19)]),
  c("nail", "Nail", "The fingertip and the nail on it",
    ["nail", "finger", "tip"], [], ["nail", "fingernail", "nail health", "fingertip"],
    "finger", [raw("M8 20V10A4 4 0 0 1 16 10V20Z", "the fingertip, rounded at the top", true), arc(12, 13, 3, 180, 360)]),
  c("posture", "Posture", "The figure standing straight",
    ["posture", "straight", "stand"], [], ["posture", "good posture", "stand straight", "back"],
    "figure", [col(4, 3, 21), disc(14, 6, 3), poly([[14, 9], [14, 15]]), poly([[10, 19], [14, 15], [18, 19]])]),
];
